"""IaC export service — generates Terraform and Pulumi configs."""


def get_supported_formats() -> list[dict]:
    return [
        {"id": "terraform", "name": "Terraform", "extension": ".tf", "description": "HashiCorp Terraform HCL configuration"},
        {"id": "pulumi", "name": "Pulumi", "extension": ".ts", "description": "Pulumi TypeScript infrastructure code"},
    ]


def generate_terraform(providers: list[str] | None = None, naming_prefix: str = "bonito") -> str:
    providers = providers or ["aws", "azure", "gcp"]
    blocks = [
        '# ============================================',
        '# Bonito AI Platform — Terraform Configuration',
        '# Generated by Bonito Export Engine',
        '# ============================================',
        '',
        'terraform {',
        '  required_version = ">= 1.5.0"',
        '  required_providers {',
    ]

    if "aws" in providers:
        blocks += [
            '    aws = {',
            '      source  = "hashicorp/aws"',
            '      version = "~> 5.0"',
            '    }',
        ]
    if "azure" in providers:
        blocks += [
            '    azurerm = {',
            '      source  = "hashicorp/azurerm"',
            '      version = "~> 3.0"',
            '    }',
        ]
    if "gcp" in providers:
        blocks += [
            '    google = {',
            '      source  = "hashicorp/google"',
            '      version = "~> 5.0"',
            '    }',
        ]

    blocks += ['  }', '}', '']

    # Variables
    blocks += [
        f'variable "project_name" {{',
        f'  default = "{naming_prefix}"',
        '}',
        '',
        'variable "environment" {',
        '  default = "production"',
        '}',
        '',
    ]

    if "aws" in providers:
        blocks += [
            'provider "aws" {',
            '  region = "us-east-1"',
            '}',
            '',
            '# ── AWS Bedrock ──────────────────────────────',
            f'resource "aws_iam_role" "{naming_prefix}_bedrock_role" {{',
            f'  name = "${{var.project_name}}-bedrock-access"',
            '  assume_role_policy = jsonencode({',
            '    Version = "2012-10-17"',
            '    Statement = [{',
            '      Action = "sts:AssumeRole"',
            '      Effect = "Allow"',
            '      Principal = { Service = "bedrock.amazonaws.com" }',
            '    }]',
            '  })',
            '}',
            '',
            f'resource "aws_iam_role_policy" "{naming_prefix}_bedrock_policy" {{',
            f'  name = "${{var.project_name}}-bedrock-invoke"',
            f'  role = aws_iam_role.{naming_prefix}_bedrock_role.id',
            '  policy = jsonencode({',
            '    Version = "2012-10-17"',
            '    Statement = [{',
            '      Effect   = "Allow"',
            '      Action   = ["bedrock:InvokeModel", "bedrock:InvokeModelWithResponseStream"]',
            '      Resource = "arn:aws:bedrock:*:*:model/*"',
            '    }]',
            '  })',
            '}',
            '',
            f'resource "aws_cloudwatch_log_group" "{naming_prefix}_bedrock_logs" {{',
            f'  name              = "/aws/bedrock/${{var.project_name}}"',
            '  retention_in_days = 90',
            '}',
            '',
        ]

    if "azure" in providers:
        blocks += [
            'provider "azurerm" {',
            '  features {}',
            '}',
            '',
            '# ── Azure AI Foundry ─────────────────────────',
            f'resource "azurerm_resource_group" "{naming_prefix}_ai_rg" {{',
            f'  name     = "${{var.project_name}}-ai-${{var.environment}}"',
            '  location = "East US"',
            '}',
            '',
            f'resource "azurerm_cognitive_account" "{naming_prefix}_openai" {{',
            f'  name                = "${{var.project_name}}-openai"',
            f'  location            = azurerm_resource_group.{naming_prefix}_ai_rg.location',
            f'  resource_group_name = azurerm_resource_group.{naming_prefix}_ai_rg.name',
            '  kind                = "OpenAI"',
            '  sku_name            = "S0"',
            '}',
            '',
            f'resource "azurerm_cognitive_deployment" "{naming_prefix}_gpt4" {{',
            f'  name                 = "gpt-4-turbo"',
            f'  cognitive_account_id = azurerm_cognitive_account.{naming_prefix}_openai.id',
            '  model {',
            '    format  = "OpenAI"',
            '    name    = "gpt-4"',
            '    version = "turbo-2024-04-09"',
            '  }',
            '  scale { type = "Standard" }',
            '}',
            '',
        ]

    if "gcp" in providers:
        blocks += [
            'provider "google" {',
            f'  project = "${{var.project_name}}-ai"',
            '  region  = "us-central1"',
            '}',
            '',
            '# ── GCP Vertex AI ───────────────────────────',
            f'resource "google_vertex_ai_endpoint" "{naming_prefix}_endpoint" {{',
            f'  display_name = "${{var.project_name}}-endpoint"',
            '  location     = "us-central1"',
            '}',
            '',
            f'resource "google_project_service" "{naming_prefix}_vertex_api" {{',
            '  service = "aiplatform.googleapis.com"',
            '}',
            '',
        ]

    # Outputs
    blocks += [
        '# ── Outputs ─────────────────────────────────',
    ]
    if "aws" in providers:
        blocks.append(f'output "bedrock_role_arn" {{ value = aws_iam_role.{naming_prefix}_bedrock_role.arn }}')
    if "azure" in providers:
        blocks.append(f'output "openai_endpoint" {{ value = azurerm_cognitive_account.{naming_prefix}_openai.endpoint }}')
    if "gcp" in providers:
        blocks.append(f'output "vertex_endpoint_id" {{ value = google_vertex_ai_endpoint.{naming_prefix}_endpoint.id }}')

    return '\n'.join(blocks)


def generate_pulumi(providers: list[str] | None = None, naming_prefix: str = "bonito") -> str:
    providers = providers or ["aws", "azure", "gcp"]
    lines = [
        '// ============================================',
        '// Bonito AI Platform — Pulumi Configuration',
        '// Generated by Bonito Export Engine',
        '// ============================================',
        '',
    ]

    imports = []
    if "aws" in providers:
        imports.append('import * as aws from "@pulumi/aws";')
    if "azure" in providers:
        imports.append('import * as azure from "@pulumi/azure-native";')
    if "gcp" in providers:
        imports.append('import * as gcp from "@pulumi/gcp";')

    lines += imports + ['', f'const projectName = "{naming_prefix}";', '']

    if "aws" in providers:
        lines += [
            '// ── AWS Bedrock ──────────────────────────────',
            'const bedrockRole = new aws.iam.Role(`${projectName}-bedrock-role`, {',
            '  assumeRolePolicy: JSON.stringify({',
            '    Version: "2012-10-17",',
            '    Statement: [{',
            '      Action: "sts:AssumeRole",',
            '      Effect: "Allow",',
            '      Principal: { Service: "bedrock.amazonaws.com" },',
            '    }],',
            '  }),',
            '});',
            '',
            'new aws.iam.RolePolicy(`${projectName}-bedrock-policy`, {',
            '  role: bedrockRole.id,',
            '  policy: JSON.stringify({',
            '    Version: "2012-10-17",',
            '    Statement: [{',
            '      Effect: "Allow",',
            '      Action: ["bedrock:InvokeModel", "bedrock:InvokeModelWithResponseStream"],',
            '      Resource: "arn:aws:bedrock:*:*:model/*",',
            '    }],',
            '  }),',
            '});',
            '',
            'const bedrockLogs = new aws.cloudwatch.LogGroup(`${projectName}-bedrock-logs`, {',
            '  retentionInDays: 90,',
            '});',
            '',
        ]

    if "azure" in providers:
        lines += [
            '// ── Azure AI Foundry ─────────────────────────',
            'const aiResourceGroup = new azure.resources.ResourceGroup(`${projectName}-ai-rg`, {',
            '  location: "eastus",',
            '});',
            '',
            'const openaiAccount = new azure.cognitiveservices.Account(`${projectName}-openai`, {',
            '  resourceGroupName: aiResourceGroup.name,',
            '  kind: "OpenAI",',
            '  sku: { name: "S0" },',
            '  location: aiResourceGroup.location,',
            '});',
            '',
        ]

    if "gcp" in providers:
        lines += [
            '// ── GCP Vertex AI ───────────────────────────',
            'const vertexEndpoint = new gcp.vertex.AiEndpoint(`${projectName}-endpoint`, {',
            '  displayName: `${projectName}-endpoint`,',
            '  location: "us-central1",',
            '});',
            '',
        ]

    lines += [
        '// ── Exports ─────────────────────────────────',
    ]
    if "aws" in providers:
        lines.append('export const bedrockRoleArn = bedrockRole.arn;')
    if "azure" in providers:
        lines.append('export const openaiEndpoint = openaiAccount.endpoint;')
    if "gcp" in providers:
        lines.append('export const vertexEndpointId = vertexEndpoint.id;')

    return '\n'.join(lines)
