import { Article } from './types';

// Seed data for SITREP - Part 4: Asia Pacific, Climate, Tech, Culture (Articles 43-50)
export const articlesPart4: Article[] = [
  // ASIA PACIFIC
  {
    id: 'apac-001',
    title: 'Japan Increases Defense Spending to 2% of GDP',
    source: 'Nikkei',
    sourceReliability: 4,
    sourceBias: 0,
    category: 'politics',
    country: 'Japan',
    countryCode: 'JP',
    lat: 35.6762,
    lng: 139.6503,
    publishedAt: '2026-03-20T05:00:00Z',
    url: 'https://example.com/article/apac-001',
    summary: 'Japan\'s parliament approved a record defense budget of $55 billion, marking the third consecutive year of increases as Tokyo responds to perceived threats from China and North Korea. The spending includes long-range missiles and cyber capabilities.',
    bsScore: 85,
    biasAnalysis: 'Nikkei provides factual business-oriented reporting on defense policy.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'apac-002',
    title: 'North Korea Tests Hypersonic Missile, Claims Successful Launch',
    source: 'Associated Press',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'conflict',
    country: 'North Korea',
    countryCode: 'KP',
    lat: 39.0392,
    lng: 125.7625,
    publishedAt: '2026-03-19T03:00:00Z',
    url: 'https://example.com/article/apac-002',
    summary: 'North Korean state media announced a successful test of a hypersonic glide vehicle capable of evading missile defenses. South Korean and US officials confirmed a launch but disputed claims of full success.',
    bsScore: 88,
    biasAnalysis: 'AP provides factual reporting with verification of North Korean claims against allied assessments.',
    credibilityTier: 1,
    isBreaking: true,
  },
  {
    id: 'apac-003',
    title: 'India Surpasses China as World\'s Most Populous Country',
    source: 'Reuters',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'politics',
    country: 'India',
    countryCode: 'IN',
    lat: 28.6139,
    lng: 77.209,
    publishedAt: '2026-03-18T06:00:00Z',
    url: 'https://example.com/article/apac-003',
    summary: 'UN demographic data confirms India\'s population has reached 1.428 billion, overtaking China\'s declining population. The milestone raises questions about India\'s ability to capitalize on its demographic dividend.',
    bsScore: 92,
    biasAnalysis: 'Reuters provides factual demographic reporting with economic implications.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'apac-004',
    title: 'Australian Mining Giants Face Pressure Over Indigenous Land Rights',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.4,
    category: 'politics',
    country: 'Australia',
    countryCode: 'AU',
    lat: -25.2744,
    lng: 133.7751,
    publishedAt: '2026-03-17T08:00:00Z',
    url: 'https://example.com/article/apac-004',
    summary: 'Rio Tinto and BHP face mounting legal challenges from Aboriginal groups over mining on traditional lands without consent. The cases could set precedents for Indigenous rights across the resources sector.',
    bsScore: 76,
    biasAnalysis: 'The Guardian emphasizes Indigenous rights perspectives with some business context.',
    credibilityTier: 2,
    isBreaking: false,
  },

  // CLIMATE/ENVIRONMENT
  {
    id: 'clm-001',
    title: 'Antarctic Ice Loss Accelerates, Threatening Coastal Cities',
    source: 'Nature',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'climate',
    country: 'Antarctica',
    countryCode: 'AQ',
    lat: -82.8628,
    lng: 135,
    publishedAt: '2026-03-20T12:00:00Z',
    url: 'https://example.com/article/clm-001',
    summary: 'A new study published in Nature confirms West Antarctic ice sheet loss has tripled since the 1990s, potentially raising sea levels by 5 meters over coming centuries. Current emissions trajectories suggest irreversible collapse may already be underway.',
    bsScore: 94,
    biasAnalysis: 'Nature provides peer-reviewed scientific reporting with minimal editorial bias.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'clm-002',
    title: 'Coral Bleaching Event Affects 70% of Great Barrier Reef',
    source: 'BBC',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'climate',
    country: 'Australia',
    countryCode: 'AU',
    lat: -18.2871,
    lng: 147.6992,
    publishedAt: '2026-03-19T10:00:00Z',
    url: 'https://example.com/article/clm-002',
    summary: 'Australian scientists confirmed the fifth mass bleaching event in eight years, with severe damage to northern reef sections. Marine biologists warn that recovery windows are shortening as ocean temperatures rise.',
    bsScore: 87,
    biasAnalysis: 'BBC provides factual environmental reporting with scientific context.',
    credibilityTier: 1,
    isBreaking: true,
  },

  // TECHNOLOGY/AI
  {
    id: 'tech-001',
    title: 'OpenAI Releases GPT-5, Claims Near-Human Reasoning',
    source: 'TechCrunch',
    sourceReliability: 3,
    sourceBias: 0.1,
    category: 'tech',
    country: 'United States',
    countryCode: 'US',
    lat: 37.7749,
    lng: -122.4194,
    publishedAt: '2026-03-20T17:00:00Z',
    url: 'https://example.com/article/tech-001',
    summary: 'OpenAI announced GPT-5 with demonstrated capabilities in complex reasoning, scientific research, and creative tasks. The company claims benchmark performance approaching human experts in multiple domains while acknowledging ongoing safety concerns.',
    bsScore: 72,
    biasAnalysis: 'TechCrunch presents tech industry announcements with some critical perspective on claims.',
    credibilityTier: 3,
    isBreaking: true,
  },
  {
    id: 'tech-002',
    title: 'EU Passes Comprehensive AI Act Enforcement Measures',
    source: 'Politico Europe',
    sourceReliability: 4,
    sourceBias: -0.1,
    category: 'tech',
    country: 'Belgium',
    countryCode: 'BE',
    lat: 50.8503,
    lng: 4.3517,
    publishedAt: '2026-03-18T14:00:00Z',
    url: 'https://example.com/article/tech-002',
    summary: 'EU member states finalized implementation rules for the AI Act, establishing fines up to 7% of global revenue for violations. Tech companies must submit risk assessments for high-risk AI systems by year\'s end.',
    bsScore: 83,
    biasAnalysis: 'Politico provides factual policy reporting with industry and civil society perspectives.',
    credibilityTier: 2,
    isBreaking: false,
  },

  // CULTURE/SOCIETY
  {
    id: 'cult-001',
    title: 'Global Box Office Hits Record High as Streaming Wars Cool',
    source: 'Variety',
    sourceReliability: 3,
    sourceBias: 0,
    category: 'culture',
    country: 'United States',
    countryCode: 'US',
    lat: 34.0928,
    lng: -118.3287,
    publishedAt: '2026-03-17T16:00:00Z',
    url: 'https://example.com/article/cult-001',
    summary: 'Theatrical revenues reached $42 billion globally in 2025, surpassing pre-pandemic levels as audiences return to cinemas. Studios are rethinking day-and-date streaming releases after several high-profile theatrical exclusives outperformed.',
    bsScore: 70,
    biasAnalysis: 'Variety provides entertainment industry reporting with business focus.',
    credibilityTier: 3,
    isBreaking: false,
  },
  {
    id: 'cult-002',
    title: 'UNESCO Warns Half of World\'s Languages Face Extinction by 2100',
    source: 'NPR',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'culture',
    country: 'France',
    countryCode: 'FR',
    lat: 48.8566,
    lng: 2.3522,
    publishedAt: '2026-03-16T11:00:00Z',
    url: 'https://example.com/article/cult-002',
    summary: 'A comprehensive UNESCO report finds that 3,000 languages are endangered, with one disappearing every two weeks. Indigenous communities and linguists are racing to document and revitalize threatened languages through technology.',
    bsScore: 81,
    biasAnalysis: 'NPR provides thoughtful coverage of cultural preservation with Indigenous perspectives.',
    credibilityTier: 1,
    isBreaking: false,
  },
];

export default articlesPart4;
