import { Article } from './types';

// Seed data for SITREP - Part 3: Africa, Latin America (Articles 31-42)
export const articlesPart3: Article[] = [
  // AFRICA
  {
    id: 'afr-001',
    title: 'Nigeria Removes Fuel Subsidy, Sparks Nationwide Protests',
    source: 'Reuters',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'economy',
    country: 'Nigeria',
    countryCode: 'NG',
    lat: 6.5244,
    lng: 3.3792,
    publishedAt: '2026-03-20T10:00:00Z',
    url: 'https://example.com/article/afr-001',
    summary: 'President Tinubu announced the removal of fuel subsidies that cost the government $10 billion annually, causing pump prices to triple overnight. Labor unions have called for indefinite strikes starting Monday.',
    bsScore: 88,
    biasAnalysis: 'Reuters provides factual reporting on economic policy with perspectives from government and unions.',
    credibilityTier: 1,
    isBreaking: true,
  },
  {
    id: 'afr-002',
    title: 'Ethiopian Forces Clash with Militants in Tigray Region',
    source: 'BBC',
    sourceReliability: 4,
    sourceBias: -0.1,
    category: 'conflict',
    country: 'Ethiopia',
    countryCode: 'ET',
    lat: 14.139,
    lng: 38.0804,
    publishedAt: '2026-03-19T08:30:00Z',
    url: 'https://example.com/article/afr-002',
    summary: 'Fresh clashes erupted between Ethiopian federal forces and Tigrayan militia groups, threatening the fragile peace agreement signed in 2022. Aid agencies report displacement of thousands of civilians in the region.',
    bsScore: 82,
    biasAnalysis: 'BBC provides balanced coverage of the conflict with humanitarian context.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'afr-003',
    title: 'South Africa\'s ANC Faces Historic Election Challenge',
    source: 'Financial Times',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'politics',
    country: 'South Africa',
    countryCode: 'ZA',
    lat: -25.7479,
    lng: 28.2293,
    publishedAt: '2026-03-18T12:00:00Z',
    url: 'https://example.com/article/afr-003',
    summary: 'Polls suggest the African National Congress could lose its parliamentary majority for the first time since apartheid ended, amid widespread dissatisfaction with corruption, unemployment, and power outages.',
    bsScore: 85,
    biasAnalysis: 'FT provides analytical coverage of political dynamics with polling data.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'afr-004',
    title: 'Kenya Launches Africa\'s Largest Wind Power Project',
    source: 'Bloomberg',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'climate',
    country: 'Kenya',
    countryCode: 'KE',
    lat: -1.2921,
    lng: 36.8219,
    publishedAt: '2026-03-17T09:00:00Z',
    url: 'https://example.com/article/afr-004',
    summary: 'The Lake Turkana Wind Power expansion adds 200MW capacity, bringing Kenya\'s renewable energy share to over 90%. The $650 million project was financed by a consortium of European development banks.',
    bsScore: 87,
    biasAnalysis: 'Bloomberg provides factual business reporting on infrastructure developments.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'afr-005',
    title: 'Congo Militia Attacks Disrupt Critical Mineral Supply Chains',
    source: 'Associated Press',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'conflict',
    country: 'Democratic Republic of Congo',
    countryCode: 'CD',
    lat: -4.4419,
    lng: 15.2663,
    publishedAt: '2026-03-16T11:00:00Z',
    url: 'https://example.com/article/afr-005',
    summary: 'CODECO militia attacks on mining operations in Ituri province have suspended cobalt and copper exports, affecting global electric vehicle battery supply chains. At least 15 miners were killed in the latest raid.',
    bsScore: 86,
    biasAnalysis: 'AP provides factual reporting on security issues with business implications.',
    credibilityTier: 1,
    isBreaking: true,
  },

  // LATIN AMERICA
  {
    id: 'lat-001',
    title: 'Mexico Elects First Female President in Historic Vote',
    source: 'Reuters',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'politics',
    country: 'Mexico',
    countryCode: 'MX',
    lat: 19.4326,
    lng: -99.1332,
    publishedAt: '2026-03-15T14:00:00Z',
    url: 'https://example.com/article/lat-001',
    summary: 'Claudia Sheinbaum claimed victory in Mexico\'s presidential election, becoming the first woman to lead the nation. She campaigned on continuing the policies of her predecessor while promising to address cartel violence.',
    bsScore: 91,
    biasAnalysis: 'Reuters provides factual election coverage with balanced candidate perspectives.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'lat-002',
    title: 'Brazilian Amazon Deforestation Hits Five-Year Low',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.4,
    category: 'climate',
    country: 'Brazil',
    countryCode: 'BR',
    lat: -3.4653,
    lng: -62.2159,
    publishedAt: '2026-03-14T10:00:00Z',
    url: 'https://example.com/article/lat-002',
    summary: 'Satellite data shows deforestation in the Brazilian Amazon decreased by 22% in the past year, attributed to strengthened environmental enforcement under President Lula\'s administration. Environmentalists caution that levels remain dangerously high.',
    bsScore: 75,
    biasAnalysis: 'The Guardian presents the development positively with environmental advocacy perspective.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'lat-003',
    title: 'Argentine Economy Contracts 3.2% as Austerity Bites',
    source: 'Financial Times',
    sourceReliability: 5,
    sourceBias: 0.1,
    category: 'economy',
    country: 'Argentina',
    countryCode: 'AR',
    lat: -34.6037,
    lng: -58.3816,
    publishedAt: '2026-03-13T12:00:00Z',
    url: 'https://example.com/article/lat-003',
    summary: 'Argentina\'s GDP shrank in Q4 as President Milei\'s deep spending cuts and currency devaluation took effect. Inflation remains above 200% despite the recession, testing public patience with the shock therapy approach.',
    bsScore: 88,
    biasAnalysis: 'FT provides analytical economic coverage with market-focused perspective.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'lat-004',
    title: 'Chile Unveils $2 Billion Green Hydrogen Investment Plan',
    source: 'Bloomberg',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'climate',
    country: 'Chile',
    countryCode: 'CL',
    lat: -33.4489,
    lng: -70.6693,
    publishedAt: '2026-03-12T09:30:00Z',
    url: 'https://example.com/article/lat-004',
    summary: 'Chile announced incentives for green hydrogen production targeting exports to Asian markets. The Atacama Desert\'s solar resources position Chile as a potential major player in the emerging clean fuel sector.',
    bsScore: 84,
    biasAnalysis: 'Bloomberg provides factual business reporting on energy investments.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'lat-005',
    title: 'Venezuelan Opposition Leader Barred From Presidential Ballot',
    source: 'Associated Press',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'politics',
    country: 'Venezuela',
    countryCode: 'VE',
    lat: 10.4806,
    lng: -66.9036,
    publishedAt: '2026-03-11T13:00:00Z',
    url: 'https://example.com/article/lat-005',
    summary: 'Venezuela\'s supreme court upheld a decision disqualifying opposition frontrunner María Corina Machado from holding office for 15 years. The move drew immediate condemnation from the US and EU as undermining electoral integrity.',
    bsScore: 89,
    biasAnalysis: 'AP provides factual reporting on political developments with international reaction context.',
    credibilityTier: 1,
    isBreaking: true,
  },

  // EUROPE
  {
    id: 'eur-001',
    title: 'German Coalition Collapses Over Budget Dispute',
    source: 'Deutsche Welle',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'politics',
    country: 'Germany',
    countryCode: 'DE',
    lat: 52.52,
    lng: 13.405,
    publishedAt: '2026-03-20T16:00:00Z',
    url: 'https://example.com/article/eur-001',
    summary: 'Chancellor Scholz\'s three-party coalition disintegrated after the Free Democrats withdrew over disagreements on deficit spending and economic reforms. Snap elections are expected within months.',
    bsScore: 84,
    biasAnalysis: 'DW provides factual reporting on domestic politics with European context.',
    credibilityTier: 2,
    isBreaking: true,
  },
  {
    id: 'eur-002',
    title: 'France Deploys Troops to New Caledonia Amid Unrest',
    source: 'BBC',
    sourceReliability: 4,
    sourceBias: -0.1,
    category: 'conflict',
    country: 'New Caledonia',
    countryCode: 'NC',
    lat: -22.2558,
    lng: 166.4505,
    publishedAt: '2026-03-19T07:00:00Z',
    url: 'https://example.com/article/eur-002',
    summary: 'French authorities declared a state of emergency in the Pacific territory after violent protests over electoral reforms. Indigenous Kanak independence activists claim the changes dilute their voting power.',
    bsScore: 81,
    biasAnalysis: 'BBC provides balanced coverage of the unrest with historical context.',
    credibilityTier: 1,
    isBreaking: false,
  },
];

export default articlesPart3;
