import { Article } from './types';

// Seed data for SITREP - Part 6: Latest News Sweep (March 31, 2026 Evening)
export const articlesPart6: Article[] = [
  // === BREAKING — CONFLICT ===
  {
    id: 'sweep-20260331-pm-001',
    title: 'US-Israel Launch Major Strikes Near Isfahan as Iran Vows Defiance',
    summary: 'Bunker-buster bombs triggered massive secondary explosions at a mountainous area near Isfahan overnight in one of the heaviest bombardments since the war began on Feb. 28. Iranian authorities maintained defiance despite significant damage to military infrastructure. The strikes come as diplomatic signals about a possible end to the conflict emerged.',
    source: 'Al Jazeera',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'conflict',
    country: 'Iran',
    countryCode: 'IR',
    lat: 32.6546,
    lng: 51.6680,
    publishedAt: '2026-03-31T08:00:00Z',
    url: 'https://www.aljazeera.com/news/2026/3/31/us-israel-launch-major-attacks-as-iranian-authorities-maintain-defiance',
    bsScore: 85,
    biasAnalysis: 'Al Jazeera reports from multiple sources with emphasis on Iranian civilian perspective; military claims require independent verification.',
    credibilityTier: 2,
    isBreaking: true,
  },
  {
    id: 'sweep-20260331-pm-002',
    title: 'Trump Lashes Out at Allies, Says Securing Strait of Hormuz Is "Not for Us"',
    summary: 'President Trump told countries including the UK to "build up some delayed courage" and reopen the Strait of Hormuz themselves, signaling a potential history-defining shift away from US alliance commitments. Defence Secretary Hegseth echoed the message, telling the "big, bad Royal Navy" to step up. The Wall Street Journal reported Trump told aides he is willing to end the campaign even if the strait remains closed.',
    source: 'Associated Press',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'conflict',
    country: 'United States',
    countryCode: 'US',
    lat: 38.9072,
    lng: -77.0369,
    publishedAt: '2026-03-31T14:00:00Z',
    url: 'https://apnews.com/article/iran-us-israel-trump-lebanon-march-31-2026-07fcd5216ceae44965de79a60a4623da',
    bsScore: 94,
    biasAnalysis: 'AP provides factual reporting with direct quotes from multiple officials; balanced coverage of diplomatic fallout.',
    credibilityTier: 1,
    isBreaking: true,
  },
  {
    id: 'sweep-20260331-pm-003',
    title: 'Israel Announces Permanent Buffer Zone in Southern Lebanon up to Litani River',
    summary: 'Defence Minister Israel Katz declared that Israel will maintain security control over southern Lebanon up to the Litani River even after the war ends, and that all houses in border villages will be demolished following the "Gaza model." Lebanon condemned the announcement as intent to impose a new occupation. At least 1,238 people have been killed in Lebanon since the ground invasion began March 2.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'conflict',
    country: 'Lebanon',
    countryCode: 'LB',
    lat: 33.8938,
    lng: 35.5018,
    publishedAt: '2026-03-31T15:00:00Z',
    url: 'https://www.bbc.com/news/articles/c5yx8knpr5no',
    bsScore: 90,
    biasAnalysis: 'BBC provides balanced reporting with statements from both Israeli and Lebanese officials; includes UN criticism and casualty figures.',
    credibilityTier: 1,
    isBreaking: true,
  },
  {
    id: 'sweep-20260331-pm-004',
    title: 'Iran Using Children in Security Roles as War Depletes Personnel',
    summary: 'An 11-year-old Iranian boy was reportedly killed in an air strike while manning a security checkpoint alongside his father in Tehran. The IRGC announced a programme called "Homeland Defender Fighters for Iran" to enrol volunteers aged 12 and above. BBC witnesses report seeing armed teenagers at checkpoints in Tehran, Karaj, and Rasht.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'conflict',
    country: 'Iran',
    countryCode: 'IR',
    lat: 35.6892,
    lng: 51.3890,
    publishedAt: '2026-03-31T13:00:00Z',
    url: 'https://www.bbc.com/news/articles/c9wqgjn7x89o',
    bsScore: 88,
    biasAnalysis: 'BBC Persian service reporting with firsthand witness accounts; IRGC-affiliated sources confirm recruitment programme.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260331-pm-005',
    title: 'US Journalist Shelly Kittleson Kidnapped in Baghdad by Iran-Backed Militia',
    summary: 'American journalist Shelly Kittleson was kidnapped in Baghdad by unknown individuals with suspected ties to Kataib Hezbollah, an Iran-backed militia group, according to Iraq\'s Interior Ministry and the US State Department. One suspect has been arrested. The abduction highlights deteriorating security for foreign press in Iraq amid the regional war.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'conflict',
    country: 'Iraq',
    countryCode: 'IQ',
    lat: 33.3152,
    lng: 44.3661,
    publishedAt: '2026-03-31T19:00:00Z',
    url: 'https://www.bbc.com/news/articles/c5yled478zwo',
    bsScore: 92,
    biasAnalysis: 'Reporting based on official government and State Department statements; militia attribution requires further confirmation.',
    credibilityTier: 1,
    isBreaking: true,
  },
  {
    id: 'sweep-20260331-pm-006',
    title: 'One Month of War on Iran Cost Arab Countries Up to $194 Billion: UNDP',
    summary: 'A UNDP report estimates the first month of the Iran war has cost Arab states up to $194 billion in economic losses. Even in a "short but intense" conflict scenario, countries like Sudan, Yemen, and Lebanon will see major increases in poverty rates. The report underscores the devastating spillover effects on already fragile economies across the region.',
    source: 'Al Jazeera',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'economy',
    country: 'Lebanon',
    countryCode: 'LB',
    lat: 33.8938,
    lng: 35.5018,
    publishedAt: '2026-03-31T12:00:00Z',
    url: 'https://www.aljazeera.com/news/2026/3/31/one-month-of-war-in-middle-east-cost-arab-states-up-to-194bn-undp',
    bsScore: 87,
    biasAnalysis: 'UNDP institutional data reported with emphasis on humanitarian consequences; figures are modeled estimates, not final audits.',
    credibilityTier: 2,
    isBreaking: false,
  },
  // === ECONOMY ===
  {
    id: 'sweep-20260331-pm-007',
    title: 'Dow Surges 1,125 Points as Wall Street Posts Best Day Since Spring',
    summary: 'The S&P 500 leaped 2.9%, the Dow rallied 2.5%, and the Nasdaq jumped 3.8% as markets seized on tenuous signals of a possible end to the Iran war. Optimism followed reports Trump told aides he is willing to end the military campaign even if the Strait of Hormuz remains closed, and Iran\'s president signaled willingness to end the war under conditions. Despite the rally, S&P 500 closed Q1 with a 4.6% loss.',
    source: 'Associated Press',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'economy',
    country: 'United States',
    countryCode: 'US',
    lat: 40.7128,
    lng: -74.0060,
    publishedAt: '2026-03-31T20:30:00Z',
    url: 'https://apnews.com/article/stock-markets-war-oil-trump-iran-84a7c46b51b3583f743c8da6a40d36ac',
    bsScore: 96,
    biasAnalysis: 'AP financial reporting based on market data; factual and well-sourced with appropriate caveats about volatility.',
    credibilityTier: 1,
    isBreaking: true,
  },
  {
    id: 'sweep-20260331-pm-008',
    title: 'US Gas Prices Top $4 a Gallon for First Time Since 2022',
    summary: 'The national average for regular gasoline hit $4.02, over a dollar more than before the Iran war began on Feb. 28 — the largest monthly jump AAA has ever recorded. Oil prices remain above $100/barrel with Brent at $103.97. An AP-NORC poll found 45% of US adults are "extremely" or "very" concerned about affording gas in coming months.',
    source: 'Associated Press',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'economy',
    country: 'United States',
    countryCode: 'US',
    lat: 38.9072,
    lng: -77.0369,
    publishedAt: '2026-03-31T16:00:00Z',
    url: 'https://apnews.com/article/gas-prices-4-gallon-iran-war-de8b7ccea254a1585cab86f336db57a6',
    bsScore: 95,
    biasAnalysis: 'AP reporting based on AAA data with consumer polling context; straightforward economic reporting.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260331-pm-009',
    title: 'Eurozone Inflation Accelerates to 2.5% as Iran War Drives Energy Prices Higher',
    summary: 'Inflation in the 21 eurozone countries rose to 2.5% in March from 1.9% in February, with energy prices surging 4.9% versus a 3.1% decline the month before. Analysts now expect the European Central Bank to raise interest rates at April and June meetings to prevent inflation from becoming entrenched. Market vendors in Rome report visible price increases on everyday goods.',
    source: 'Associated Press',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'economy',
    country: 'Germany',
    countryCode: 'DE',
    lat: 50.1109,
    lng: 8.6821,
    publishedAt: '2026-03-31T10:00:00Z',
    url: 'https://apnews.com/article/eurozone-inflation-european-central-bank-60235b6abb95eed27ad3f30280f8fa71',
    bsScore: 94,
    biasAnalysis: 'AP reports Eurostat official data with ECB policy context; includes real-world consumer impact anecdotes.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260331-pm-010',
    title: 'US Hiring Drops to Pandemic-Era Lows as Job Market Stagnates Under Trump',
    summary: 'Labour market stagnation deepens as private payroll growth averages just 18,000 monthly in recent months, the weakest pace since the COVID-19 pandemic. The slowdown reflects broader economic uncertainty driven by the Iran war, high fuel costs, and trade policy concerns heading into midterm elections.',
    source: 'Al Jazeera',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'economy',
    country: 'United States',
    countryCode: 'US',
    lat: 38.9072,
    lng: -77.0369,
    publishedAt: '2026-03-31T14:30:00Z',
    url: 'https://www.aljazeera.com/economy/2026/3/31/hiring-in-the-us-drops-to-pandemic-lows-as-job-market-under-trump-stagnates',
    bsScore: 86,
    biasAnalysis: 'Al Jazeera economic reporting with headline framing that attributes stagnation to administration; data itself is factual.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'sweep-20260331-pm-011',
    title: 'McCormick Acquires Unilever Food Division in $44.8 Billion Mega-Merger',
    summary: 'Spice maker McCormick will combine with Unilever\'s food business — including Hellmann\'s, Knorr, and other major brands — in a deal valuing the combined entity at $44.8 billion. Unilever shareholders will own 65% of the merged company. The deal is the latest in a wave of packaged food consolidation as companies contend with inflation and shifting consumer tastes.',
    source: 'Associated Press',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'economy',
    country: 'United States',
    countryCode: 'US',
    lat: 39.2904,
    lng: -76.6122,
    publishedAt: '2026-03-31T13:00:00Z',
    url: 'https://apnews.com/article/unilever-mccormick-merger-spices-d395e09cc4637177bcfb7cf0f8ce6202',
    bsScore: 96,
    biasAnalysis: 'AP corporate reporting with deal terms sourced from official company announcements; factual and well-sourced.',
    credibilityTier: 1,
    isBreaking: false,
  },
  // === POLITICS ===
  {
    id: 'sweep-20260331-pm-012',
    title: 'Gulf Allies Privately Urge Trump to Keep Fighting Until Iran Is Decisively Defeated',
    summary: 'Saudi Arabia, UAE, Kuwait, and Bahrain are privately making the case to the White House that the monthlong bombing campaign should not end until there are significant changes in Iranian leadership or behaviour. The push comes as Trump vacillates between claiming Iran is ready to settle and threatening further escalation. Over 3,000 people have been killed across the region.',
    source: 'Associated Press',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'politics',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    lat: 24.7136,
    lng: 46.6753,
    publishedAt: '2026-03-31T17:00:00Z',
    url: 'https://apnews.com/article/trump-iran-saudi-arabia-mbs-gulf-war-uae-89f690b952fe28d3140c537b70fa5051',
    bsScore: 90,
    biasAnalysis: 'AP uses anonymous sourcing from US, Gulf, and Israeli officials; transparent about sourcing methodology.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260331-pm-013',
    title: 'Iran\'s FM Confirms Contact with US Envoy Witkoff but Denies Formal Negotiations',
    summary: 'Iran\'s Foreign Minister Araghchi told Al Jazeera that while contacts with US envoy Witkoff have occurred, Iran is not in formal negotiations with the United States. Araghchi maintained that Iran has "the necessary will to end the war" as long as certain requirements are met, including guarantees against future aggression.',
    source: 'Al Jazeera',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'politics',
    country: 'Iran',
    countryCode: 'IR',
    lat: 35.6892,
    lng: 51.3890,
    publishedAt: '2026-03-31T11:00:00Z',
    url: 'https://www.aljazeera.com/news/2026/3/31/no-truth-to-us-iranian-negotiations-irans-fm-tells-al-jazeera',
    bsScore: 84,
    biasAnalysis: 'Al Jazeera exclusive interview with Iranian FM; provides direct Iranian government perspective that should be weighed against other sources.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'sweep-20260331-pm-014',
    title: 'Sanctioned Russian Tanker Docks in Cuba After US Allows Passage Despite Energy Blockade',
    summary: 'The Russian tanker Anatoly Kolodkin docked at the Cuban port of Matanzas carrying 730,000 barrels of oil — the first oil tanker to reach the island in three months. Cuba produces barely 40% of its required fuel and faces long blackouts and severe shortages. The Trump administration allowed the vessel to pass despite an ongoing energy blockade.',
    source: 'Associated Press',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'politics',
    country: 'Cuba',
    countryCode: 'CU',
    lat: 23.1136,
    lng: -82.3666,
    publishedAt: '2026-03-31T15:00:00Z',
    url: 'https://apnews.com/article/cuba-russia-oil-sanctions-blockade-us-trump-1b69b79b322586503d08f28882e5b948',
    bsScore: 93,
    biasAnalysis: 'AP on-the-ground reporting from Matanzas with quotes from Cuban officials and residents; factual and balanced.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260331-pm-015',
    title: 'Pakistan Emerges as Unlikely Mediator in Iran War as Field Marshal Munir Gains Trump\'s Favour',
    summary: 'Pakistan has positioned itself as an intermediary between the US and Iran, leveraging its 900km shared border with Iran and military chief Field Marshal Asim Munir\'s relationship with Trump, who calls him his "favourite." Pakistan faces its own pressures — it raised petrol prices 20% in March and introduced a four-day government work week to conserve fuel.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'politics',
    country: 'Pakistan',
    countryCode: 'PK',
    lat: 33.6844,
    lng: 73.0479,
    publishedAt: '2026-03-31T03:00:00Z',
    url: 'https://www.bbc.com/news/articles/cy91vrzxn34o',
    bsScore: 88,
    biasAnalysis: 'BBC analysis with expert quotes from Atlantic Council; presents Pakistan\'s balancing act with appropriate context of its own regional conflicts.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260331-pm-016',
    title: 'Judge Temporarily Halts Trump White House Ballroom Construction Project',
    summary: 'A Republican-appointed federal judge ruled that Trump exceeded his authority by beginning construction on a White House ballroom without Congressional approval. Judge Richard Leon wrote that the president is "the steward of the White House for future generations" but "not the owner." The order takes effect in 14 days, allowing for appeal.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'politics',
    country: 'United States',
    countryCode: 'US',
    lat: 38.8977,
    lng: -77.0365,
    publishedAt: '2026-03-31T22:00:00Z',
    url: 'https://www.bbc.com/news/articles/c7056exw78xo',
    bsScore: 93,
    biasAnalysis: 'BBC legal reporting with direct quotes from the ruling; notes the judge\'s Republican appointment for context.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260331-pm-017',
    title: 'Federal Judge Rules Trump Unlawfully Terminated Legal Status of 900,000 Migrants',
    summary: 'A federal judge ruled that the Department of Homeland Security overstepped its authority when it terminated the legal parole status of roughly 900,000 migrants who entered the US using the Biden-era CBP One app. The ruling restores status nationwide to affected individuals. The Trump administration is expected to appeal.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'politics',
    country: 'United States',
    countryCode: 'US',
    lat: 42.3601,
    lng: -71.0589,
    publishedAt: '2026-03-31T19:00:00Z',
    url: 'https://www.bbc.com/news/articles/c4g6rmlp2l5o',
    bsScore: 92,
    biasAnalysis: 'BBC legal reporting with factual coverage of the ruling; includes context of broader immigration crackdown.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260331-pm-018',
    title: 'Trump Administration to Close Historic Montana-Alberta Border Road',
    summary: 'The US government will close a 9-mile stretch of Border Road between Montana and Alberta from July 1, ending more than eight decades of informal crossings between farming communities. The Trump administration cites rising irregular migration and drug smuggling. Alberta is spending C$8 million to build a replacement road on the Canadian side.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'politics',
    country: 'United States',
    countryCode: 'US',
    lat: 48.9986,
    lng: -111.9600,
    publishedAt: '2026-03-31T17:00:00Z',
    url: 'https://www.bbc.com/news/articles/cly7gl95nnpo',
    bsScore: 90,
    biasAnalysis: 'BBC reporting with local community voices from both sides of the border; factual coverage of policy decision.',
    credibilityTier: 1,
    isBreaking: false,
  },
  // === TECH ===
  {
    id: 'sweep-20260331-pm-019',
    title: 'Nvidia Invests $2 Billion in Marvell Technology, Announces Major Partnership',
    summary: 'Nvidia invested $2 billion in chipmaker Marvell Technology and announced a strategic partnership, sending Marvell shares up 12.8% and Nvidia up 5.6%. The deal was a major driver of Tuesday\'s tech-led market rally, with Nvidia being the single strongest force lifting the S&P 500. The partnership deepens ties in the AI semiconductor supply chain.',
    source: 'Associated Press',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'tech',
    country: 'United States',
    countryCode: 'US',
    lat: 37.3861,
    lng: -122.0839,
    publishedAt: '2026-03-31T18:00:00Z',
    url: 'https://apnews.com/article/stock-markets-war-oil-trump-iran-84a7c46b51b3583f743c8da6a40d36ac',
    bsScore: 95,
    biasAnalysis: 'AP financial reporting based on market data and corporate announcements; factual and well-sourced.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260331-pm-020',
    title: 'Eli Lilly Acquires Centessa Pharmaceuticals for Up to $7.8 Billion',
    summary: 'Pharmaceutical giant Eli Lilly announced the acquisition of Centessa Pharmaceuticals, which is developing treatments for excessive daytime sleepiness and other neurological conditions, in a deal worth up to $7.8 billion if certain conditions are met. Centessa shares soared 44% on the news. The deal expands Lilly\'s neurological treatment portfolio.',
    source: 'Associated Press',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'economy',
    country: 'United States',
    countryCode: 'US',
    lat: 39.7684,
    lng: -86.1581,
    publishedAt: '2026-03-31T14:00:00Z',
    url: 'https://apnews.com/article/stock-markets-war-oil-trump-iran-84a7c46b51b3583f743c8da6a40d36ac',
    bsScore: 95,
    biasAnalysis: 'AP reporting of corporate M&A activity based on official announcements; straightforward financial journalism.',
    credibilityTier: 1,
    isBreaking: false,
  },
  // === CULTURE ===
  {
    id: 'sweep-20260331-pm-021',
    title: 'Italy Fails to Qualify for World Cup for Third Consecutive Time After Bosnia Shootout',
    summary: 'Four-time World Cup winners Italy were eliminated in a penalty shootout by Bosnia-Herzegovina, becoming the first former champions to miss three consecutive tournaments. Italy had taken the lead through Moise Kean but were reduced to 10 men after Alessandro Bastoni\'s red card. Bosnia will face Canada, Qatar, and Switzerland in Group B this summer.',
    source: 'BBC Sport',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'culture',
    country: 'Italy',
    countryCode: 'IT',
    lat: 43.8564,
    lng: 18.4131,
    publishedAt: '2026-03-31T21:00:00Z',
    url: 'https://www.bbc.com/sport/football/live/c208ge6p142t',
    bsScore: 98,
    biasAnalysis: 'Factual sports reporting of match result; no political framing.',
    credibilityTier: 1,
    isBreaking: true,
  },
  {
    id: 'sweep-20260331-pm-022',
    title: 'UK Sends More Troops and Air Defence Systems to Middle East',
    summary: 'The UK government announced it will deploy additional troops and air defence systems to Middle Eastern allies, responding to the escalating Iran conflict. The announcement came on the same day Trump publicly berated Britain for not doing enough to secure the Strait of Hormuz, heightening tensions within the Western alliance.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'conflict',
    country: 'United Kingdom',
    countryCode: 'GB',
    lat: 51.5074,
    lng: -0.1278,
    publishedAt: '2026-03-31T16:00:00Z',
    url: 'https://www.bbc.com/news/articles/c7vq76g45rvo',
    bsScore: 91,
    biasAnalysis: 'BBC defence reporting with government sources; contextualizes UK deployment within broader alliance tensions.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260331-pm-023',
    title: 'Hezbollah Backs Iranian Ambassador as Lebanon Rift Deepens Over Expulsion',
    summary: 'Hezbollah has backed Iran\'s ambassador to Lebanon after the Lebanese government moved to expel him, exposing deep fractures in the country\'s fragile political system. The standoff tests the limits of state power as Hezbollah resists disarmament demands amid Israel\'s expanding military operations in southern Lebanon.',
    source: 'Al Jazeera',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'politics',
    country: 'Lebanon',
    countryCode: 'LB',
    lat: 33.8938,
    lng: 35.5018,
    publishedAt: '2026-03-31T10:00:00Z',
    url: 'https://www.aljazeera.com/news/2026/3/31/analysis-hezbollah-backs-iran-ambassador-as-conflict-deepens-lebanon-rifts',
    bsScore: 83,
    biasAnalysis: 'Al Jazeera analysis piece examining internal Lebanese politics; provides multiple factional perspectives.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'sweep-20260331-pm-024',
    title: 'US Supreme Court Strikes Down Colorado Ban on Conversion Therapy',
    summary: 'The US Supreme Court struck down Colorado\'s ban on conversion therapy in a ruling with significant implications for state-level LGBTQ+ protections. The decision could affect similar bans in other states and marks a major shift in the court\'s approach to regulating therapeutic practices targeting sexual orientation and gender identity.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'politics',
    country: 'United States',
    countryCode: 'US',
    lat: 38.9072,
    lng: -77.0369,
    publishedAt: '2026-03-31T18:00:00Z',
    url: 'https://www.bbc.com/news/articles/c1j75rz77x5o',
    bsScore: 93,
    biasAnalysis: 'BBC legal reporting of Supreme Court decision; factual coverage of ruling with context on broader implications.',
    credibilityTier: 1,
    isBreaking: false,
  },
  // === RETAINED FROM PREVIOUS SWEEPS ===
  {
    id: 'sweep-20260327-am-001',
    title: 'Israel Says It Killed Iran\'s Navy Chief Overseeing Strait of Hormuz Blockade',
    summary: 'Israel announced it has killed the Iranian navy chief responsible for the blockade of the Strait of Hormuz, one of the world\'s busiest oil shipping channels. The strait has been effectively blocked by Iran since the outbreak of war last month, causing a global energy crisis.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'conflict',
    country: 'Israel',
    countryCode: 'IL',
    lat: 31.7683,
    lng: 35.2137,
    publishedAt: '2026-03-26T08:00:00Z',
    url: 'https://www.bbc.com/news/live/cre0vl84qy9t',
    bsScore: 85,
    biasAnalysis: 'BBC reports Israeli military claims with appropriate attribution; casualty claims from conflict zone require verification.',
    credibilityTier: 1,
    isBreaking: true,
  },
  {
    id: 'sweep-20260327-am-003',
    title: 'Meta and YouTube Found Liable in Landmark Social Media Addiction Trial',
    summary: 'A Los Angeles jury awarded $6 million in damages after finding Meta and Google intentionally designed addictive platforms that harmed a 20-year-old\'s mental health. Meta will pay 70% and Google 30%. The verdict could impact hundreds of similar cases and has prompted UK Prime Minister Starmer to say "things are going to change" regarding child social media protections.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'tech',
    country: 'United States',
    countryCode: 'US',
    lat: 34.0522,
    lng: -118.2437,
    publishedAt: '2026-03-26T10:00:00Z',
    url: 'https://www.bbc.com/news/articles/c747x7gz249o',
    bsScore: 92,
    biasAnalysis: 'Comprehensive reporting includes corporate responses and international implications; balanced coverage of landmark verdict.',
    credibilityTier: 1,
    isBreaking: true,
  },
  {
    id: 'sweep-20260323-008',
    title: 'Strike on Sudan Hospital Kills at Least 64, WHO Reports',
    summary: 'An army drone attack on a health facility in East Darfur killed at least 64 people and wounded 89 more, according to the WHO. Victims included children and medical personnel. The strike has been widely condemned by international humanitarian organizations.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'conflict',
    country: 'Sudan',
    countryCode: 'SD',
    lat: 11.7500,
    lng: 26.0500,
    publishedAt: '2026-03-23T10:00:00Z',
    url: 'https://www.theguardian.com/world/2026/mar/23/strike-sudan-hospital-kills-who',
    bsScore: 90,
    biasAnalysis: 'Reporting based on WHO official data with emphasis on civilian casualties and international law violations.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260323-006',
    title: 'IEA Chief: Iran War Energy Crunch Worse Than 1970s Oil Crises',
    summary: 'The International Energy Agency chief warned that the energy disruption caused by the Iran conflict is more severe than both the 1970s oil crises and the Ukraine war combined. IEA members agreed to release 400 million barrels from strategic reserves to stabilize markets.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'economy',
    country: 'France',
    countryCode: 'FR',
    lat: 48.8566,
    lng: 2.3522,
    publishedAt: '2026-03-23T13:00:00Z',
    url: 'https://www.theguardian.com/world/live/2026/mar/23/middle-east-crisis-live-iea-chief-says-iran-war-energy-crunch-worse-than-1970s-oil-crises',
    bsScore: 88,
    biasAnalysis: 'Reporting relies on IEA institutional analysis with factual framing of energy market implications.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260327-am-010',
    title: 'Australia Growth Forecasts Slashed as Global Economy Faces Inflation Spike',
    summary: 'The OECD has slashed Australian growth forecasts, warning the Middle East war will test global resilience with Australia expected to suffer from higher interest rates and inflation. The report predicts the Iran conflict could push the world economy toward stagflation as energy prices remain elevated through 2026.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'economy',
    country: 'Australia',
    countryCode: 'AU',
    lat: -33.8688,
    lng: 151.2093,
    publishedAt: '2026-03-26T07:00:00Z',
    url: 'https://www.theguardian.com/world/2026/mar/26/australia-growth-forecasts-slashed-oecd-iran-war',
    bsScore: 89,
    biasAnalysis: 'Economic analysis based on OECD institutional data; appropriately cautious about stagflation predictions.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260327-am-006',
    title: 'UN Votes to Recognize Enslavement of Africans as \'Gravest Crime Against Humanity\'',
    summary: 'The UN General Assembly passed a landmark resolution describing the slave trade as the "gravest crime against humanity." The resolution calls for an apology and contributions to a reparations fund, though without specifying amounts. The vote marks a historic international acknowledgment of transatlantic slavery\'s legacy.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'politics',
    country: 'United States',
    countryCode: 'US',
    lat: 40.7128,
    lng: -74.0060,
    publishedAt: '2026-03-26T06:00:00Z',
    url: 'https://www.bbc.com/news/articles/cvg06q36052o',
    bsScore: 94,
    biasAnalysis: 'Straightforward institutional reporting on UN resolution with historic context.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260323-024',
    title: 'China Has Been Preparing for a Global Energy Crisis for Years. It Is Paying Off Now',
    summary: 'As the Iran war drives global energy prices to crisis levels, China\'s years of strategic investment in domestic renewable energy, nuclear power, and strategic petroleum reserves are insulating it from the worst supply shocks hitting Western economies.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'economy',
    country: 'China',
    countryCode: 'CN',
    lat: 39.9042,
    lng: 116.4074,
    publishedAt: '2026-03-23T08:30:00Z',
    url: 'https://www.theguardian.com/world/2026/mar/23/china-energy-crisis-preparation',
    bsScore: 80,
    biasAnalysis: 'Analysis piece examining Chinese energy strategy with implicit criticism of Western unpreparedness.',
    credibilityTier: 2,
    isBreaking: false,
  },
];
