import { Article } from './types';

// Seed data for SITREP - Part 5: Foreign Language Sources (AI Translation Showcase)
export const articlesPart5: Article[] = [
  // JAPAN - NHK
  {
    id: 'intl-001',
    title: 'Japan Approves Record Defense Budget Amid Regional Tensions',
    originalTitle: '日本政府、過去最大の防衛予算を承認 地域の緊張高まる中',
    summary: 'The Japanese cabinet approved a record ¥7.9 trillion defense budget for fiscal 2026, marking the third consecutive year of increases exceeding 10%. The budget includes funding for counterstrike capabilities and advanced missile defense systems amid growing concerns over North Korean and Chinese military activities.',
    source: 'NHK World-Japan',
    sourceReliability: 4,
    sourceBias: 0.1,
    category: 'politics',
    country: 'Japan',
    countryCode: 'JP',
    lat: 35.6762,
    lng: 139.6503,
    publishedAt: '2026-03-20T03:00:00Z',
    url: 'https://www3.nhk.or.jp/nhkworld/en/news/2026/0320-defense.html',
    bsScore: 84,
    biasAnalysis: 'NHK provides factual government reporting with minimal editorial framing.',
    credibilityTier: 1,
    isBreaking: false,
    originalLanguage: 'ja',
  },

  // GERMANY - Der Spiegel
  {
    id: 'intl-002',
    title: 'German Industrial Output Falls for Fifth Consecutive Month',
    originalTitle: 'Deutsche Industrieproduktion sinkt zum fünften Monat in Folge',
    summary: 'German industrial production dropped 2.1% in February, extending a concerning downward trend that economists warn could push Europe\'s largest economy into recession. The automotive and chemical sectors showed the steepest declines, with energy costs and weak export demand cited as primary factors.',
    source: 'Der Spiegel',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'economy',
    country: 'Germany',
    countryCode: 'DE',
    lat: 52.52,
    lng: 13.405,
    publishedAt: '2026-03-19T08:00:00Z',
    url: 'https://www.spiegel.de/wirtschaft/industrieproduktion-deutschland-2026.html',
    bsScore: 86,
    biasAnalysis: 'Der Spiegel provides analytical economic coverage with center-left perspective on labor impacts.',
    credibilityTier: 2,
    isBreaking: false,
    originalLanguage: 'de',
  },

  // FRANCE - Le Monde
  {
    id: 'intl-003',
    title: 'France Expands Nuclear Energy Program Despite Green Party Opposition',
    originalTitle: 'La France élargit son programme nucléaire malgré l\'opposition des écologistes',
    summary: 'President Macron announced plans to construct six new EPR2 nuclear reactors by 2040, with an option for eight additional units. The decision marks a significant reversal of the 2015 energy transition law and faces strong opposition from environmental groups and coalition partners.',
    source: 'Le Monde',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'climate',
    country: 'France',
    countryCode: 'FR',
    lat: 48.8566,
    lng: 2.3522,
    publishedAt: '2026-03-18T14:30:00Z',
    url: 'https://www.lemonde.fr/economie/article/2026/nucleaire-france-epr2.html',
    bsScore: 82,
    biasAnalysis: 'Le Monde presents balanced coverage of energy policy with emphasis on environmental concerns.',
    credibilityTier: 2,
    isBreaking: false,
    originalLanguage: 'fr',
  },

  // BRAZIL - Folha de São Paulo
  {
    id: 'intl-004',
    title: 'Amazon Deforestation Drops 40% in First Quarter Under New Enforcement',
    originalTitle: 'Desmatamento na Amazônia cai 40% no primeiro trimestre sob nova fiscalização',
    summary: 'Satellite data from INPE shows a significant reduction in forest clearing compared to the same period last year. The decline is attributed to renewed enforcement operations by IBAMA and increased use of real-time monitoring technology to detect illegal logging operations.',
    source: 'Folha de S.Paulo',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'climate',
    country: 'Brazil',
    countryCode: 'BR',
    lat: -3.4653,
    lng: -62.2159,
    publishedAt: '2026-03-17T10:00:00Z',
    url: 'https://www1.folha.uol.com.br/ambiente/2026/03/amazonia-desmatamento.html',
    bsScore: 79,
    biasAnalysis: 'Folha provides factual environmental reporting with cautious optimism on government claims.',
    credibilityTier: 2,
    isBreaking: false,
    originalLanguage: 'pt',
  },

  // SAUDI ARABIA - Al Arabiya
  {
    id: 'intl-005',
    title: 'Saudi Arabia Unveils $100 Billion AI Investment Initiative',
    originalTitle: 'السعودية تكشف عن مبادرة استثمارية في الذكاء الاصطناعي بقيمة 100 مليار دولار',
    summary: 'Crown Prince Mohammed bin Salman announced "Project Transcendence," a massive public-private partnership to establish the Kingdom as a global AI hub. The initiative includes data center construction, semiconductor manufacturing partnerships, and talent recruitment from leading technology firms.',
    source: 'Al Arabiya English',
    sourceReliability: 3,
    sourceBias: 0.4,
    category: 'tech',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    lat: 24.7136,
    lng: 46.6753,
    publishedAt: '2026-03-16T12:00:00Z',
    url: 'https://english.alarabiya.net/business/technology/2026/03/16/saudi-ai-100-billion',
    bsScore: 72,
    biasAnalysis: 'Al Arabiya presents official announcements positively with limited critical perspective.',
    credibilityTier: 3,
    isBreaking: true,
    originalLanguage: 'ar',
  },

  // CHINA - Xinhua
  {
    id: 'intl-006',
    title: 'China Launches New Space Station Module, Expanding Orbital Research Capabilities',
    originalTitle: '中国发射新空间站舱段 扩展在轨研究能力',
    summary: 'The Wentian-2 module successfully docked with the Tiangong space station, providing additional living quarters and expanded laboratory space. The mission represents the latest step in China\'s ambitious space program, which aims to establish a permanent lunar presence by 2030.',
    source: 'Xinhua News Agency',
    sourceReliability: 3,
    sourceBias: 0.3,
    category: 'tech',
    country: 'China',
    countryCode: 'CN',
    lat: 39.9042,
    lng: 116.4074,
    publishedAt: '2026-03-15T06:00:00Z',
    url: 'http://www.xinhuanet.com/english/2026-03/15/c_1310754321.htm',
    bsScore: 70,
    biasAnalysis: 'Xinhua reports factual mission details with nationalistic framing on space achievements.',
    credibilityTier: 3,
    isBreaking: false,
    originalLanguage: 'zh',
  },

  // SPAIN - El País
  {
    id: 'intl-007',
    title: 'Spanish Tourism Hits Record Numbers as Visitor Spending Surges',
    originalTitle: 'El turismo español bate récords mientras el gasto de los visitantes se dispara',
    summary: 'Spain welcomed 8.5 million international visitors in February, a 15% increase year-over-year, with average spending per tourist reaching €1,240. The data underscores the sector\'s recovery and its growing importance to the national economy despite concerns about overtourism in Barcelona and the Balearic Islands.',
    source: 'El País',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'economy',
    country: 'Spain',
    countryCode: 'ES',
    lat: 40.4168,
    lng: -3.7038,
    publishedAt: '2026-03-14T09:00:00Z',
    url: 'https://elpais.com/economia/2026-03-14/turismo-espana-record.html',
    bsScore: 81,
    biasAnalysis: 'El País provides balanced economic reporting with attention to social impacts of tourism.',
    credibilityTier: 2,
    isBreaking: false,
    originalLanguage: 'es',
  },

  // SOUTH KOREA - Chosun Ilbo
  {
    id: 'intl-008',
    title: 'South Korea Approves Chaebol Reform Bill After Political Standoff',
    originalTitle: '정치적 대립 끝에 국회, 재벌 개혁법안 통과시켜',
    summary: 'The National Assembly passed legislation strengthening minority shareholder rights and increasing transparency requirements for conglomerates after weeks of filibustering. The ruling party opposed the measure, arguing it would hurt competitiveness, while opposition parties hailed it as a victory for corporate governance reform.',
    source: 'The Chosun Ilbo',
    sourceReliability: 3,
    sourceBias: 0.2,
    category: 'politics',
    country: 'South Korea',
    countryCode: 'KR',
    lat: 37.5665,
    lng: 126.978,
    publishedAt: '2026-03-13T11:00:00Z',
    url: 'https://english.chosun.com/site/data/html_dir/2026/03/13/2026031301234.html',
    bsScore: 76,
    biasAnalysis: 'Chosun Ilbo leans conservative in coverage but provides factual legislative reporting.',
    credibilityTier: 3,
    isBreaking: false,
    originalLanguage: 'ko',
  },

  // RUSSIA - TASS (through translation)
  {
    id: 'intl-009',
    title: 'Russia Increases Oil Production Despite OPEC+ Quotas',
    originalTitle: 'Россия нарастила добычу нефти вопреки квотам ОПЕК+',
    summary: 'Russian oil output rose to 9.6 million barrels per day in February, exceeding agreed production limits by approximately 200,000 barrels. The increase comes as Moscow seeks to replenish state coffers amid sustained military expenditures and Western sanctions pressure.',
    source: 'Kommersant',
    sourceReliability: 3,
    sourceBias: 0.3,
    category: 'economy',
    country: 'Russia',
    countryCode: 'RU',
    lat: 55.7558,
    lng: 37.6173,
    publishedAt: '2026-03-12T08:00:00Z',
    url: 'https://www.kommersant.ru/doc/12345678',
    bsScore: 68,
    biasAnalysis: 'Kommersant provides business-focused reporting with careful navigation of state interests.',
    credibilityTier: 3,
    isBreaking: false,
    originalLanguage: 'ru',
  },

  // INDIA - The Hindu
  {
    id: 'intl-010',
    title: 'Indian Parliament Passes Controversial Data Protection Amendment',
    originalTitle: 'भारतीय संसद ने विवादास्पद डेटा संरक्षण संशोधन पारित किया',
    summary: 'Lok Sabha approved changes to the Digital Personal Data Protection Act that critics say weaken privacy safeguards and expand government surveillance powers. Opposition parties walked out of the chamber in protest, while the government argued the amendments are necessary for national security.',
    source: 'The Hindu',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'tech',
    country: 'India',
    countryCode: 'IN',
    lat: 28.6139,
    lng: 77.209,
    publishedAt: '2026-03-11T14:00:00Z',
    url: 'https://www.thehindu.com/sci-tech/technology/data-protection-amendment-2026/article12345678.ece',
    bsScore: 83,
    biasAnalysis: 'The Hindu provides balanced coverage of technology policy with civil liberties perspective.',
    credibilityTier: 2,
    isBreaking: false,
    originalLanguage: 'hi',
  },
];

export default articlesPart5;
