import { Article } from './types';

// Seed data for SITREP - Part 6: Latest News Sweep (March 26, 2026 Morning)
export const articlesPart6: Article[] = [
  // BREAKING - CONFLICT
  {
    id: 'sweep-20260326-am-001',
    title: 'Israel Says It Killed Iran\'s Navy Chief Overseeing Strait of Hormuz Blockade',
    summary: 'Israel announced it has killed the Iranian navy chief responsible for the blockade of the Strait of Hormuz, one of the world\'s busiest oil shipping channels. The strait has been effectively blocked by Iran since the outbreak of war last month, causing a global energy crisis.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'conflict',
    country: 'Israel',
    countryCode: 'IL',
    lat: 31.7683,
    lng: 35.2137,
    publishedAt: '2026-03-26T08:00:00Z',
    url: 'https://www.bbc.com/news/live/cre0vl84qy9t',
    bsScore: 85,
    biasAnalysis: 'BBC reports Israeli military claims with appropriate attribution; casualty claims from conflict zone require verification.',
    credibilityTier: 1,
    isBreaking: true,
  },
  {
    id: 'sweep-20260326-am-002',
    title: 'Trump Confirms May Meeting with Xi Jinping as Iran War Forces Postponement',
    summary: 'President Trump will meet Chinese President Xi Jinping in China on May 14-15, marking the first US presidential visit in nearly 10 years. The trip was delayed from March 31 due to the US-Israel war with Iran. Xi is expected to visit Washington later this year for a reciprocal meeting.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'politics',
    country: 'China',
    countryCode: 'CN',
    lat: 39.9042,
    lng: 116.4074,
    publishedAt: '2026-03-26T04:00:00Z',
    url: 'https://www.bbc.com/news/articles/c05dpr1m71go',
    bsScore: 90,
    biasAnalysis: 'Factual reporting on diplomatic scheduling; notes Beijing has not officially confirmed dates per standard protocol.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260326-am-003',
    title: 'Meta and YouTube Found Liable in Landmark Social Media Addiction Trial',
    summary: 'A Los Angeles jury awarded $6 million in damages after finding Meta and Google intentionally designed addictive platforms that harmed a 20-year-old\'s mental health. Meta will pay 70% and Google 30%. The verdict could impact hundreds of similar cases and has prompted UK Prime Minister Starmer to say "things are going to change" regarding child social media protections.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'tech',
    country: 'United States',
    countryCode: 'US',
    lat: 34.0522,
    lng: -118.2437,
    publishedAt: '2026-03-26T10:00:00Z',
    url: 'https://www.bbc.com/news/articles/c747x7gz249o',
    bsScore: 92,
    biasAnalysis: 'Comprehensive reporting includes corporate responses and international implications; balanced coverage of landmark verdict.',
    credibilityTier: 1,
    isBreaking: true,
  },
  {
    id: 'sweep-20260326-am-004',
    title: 'India Passes Controversial Bill Amending Transgender Rights Amid Protests',
    summary: 'India\'s parliament passed a bill that removes the right to self-identify for transgender people, instead requiring medical certification and limiting recognition to those with biological or physical traits. Critics warn the amendment could exclude many trans men, women, and non-binary people from legal protections.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'politics',
    country: 'India',
    countryCode: 'IN',
    lat: 28.6139,
    lng: 77.2090,
    publishedAt: '2026-03-26T07:00:00Z',
    url: 'https://www.bbc.com/news/articles/czx9de4ygl7o',
    bsScore: 88,
    biasAnalysis: 'Balanced coverage presents both government rationale (welfare targeting) and activist opposition (identity concerns).',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260326-am-005',
    title: 'Are US-Iran Peace Talks Really Taking Place?',
    summary: 'Despite Trump\'s claims of negotiating with Iran, Tehran repeatedly denies talks are occurring. Iran\'s Foreign Minister Abbas Araghchi admits messages have been exchanged via intermediaries but insists these constitute "neither dialogue nor negotiation." The 15-point US plan demands Iran end its nuclear and ballistic missile programs; Iran\'s counter-demands include war reparations and sovereignty over the Strait of Hormuz.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'conflict',
    country: 'Iran',
    countryCode: 'IR',
    lat: 35.6892,
    lng: 51.3890,
    publishedAt: '2026-03-26T09:00:00Z',
    url: 'https://www.bbc.com/news/articles/cm29l9r68j8o',
    bsScore: 87,
    biasAnalysis: 'Analytical piece comparing stated positions from both sides; acknowledges verification challenges in closed-door diplomacy.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260326-am-006',
    title: 'UN Votes to Recognize Enslavement of Africans as \'Gravest Crime Against Humanity\'',
    summary: 'The UN General Assembly passed a landmark resolution describing the slave trade as the "gravest crime against humanity." The resolution calls for an apology and contributions to a reparations fund, though without specifying amounts. The vote marks a historic international acknowledgment of transatlantic slavery\'s legacy.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'politics',
    country: 'United States',
    countryCode: 'US',
    lat: 40.7128,
    lng: -74.0060,
    publishedAt: '2026-03-26T06:00:00Z',
    url: 'https://www.bbc.com/news/articles/cvg06q36052o',
    bsScore: 94,
    biasAnalysis: 'Straightforward institutional reporting on UN resolution with historic context.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260326-am-007',
    title: 'Zimbabwe Says 15 Nationals Killed After Being Lured to Fight for Russia',
    summary: 'Zimbabwe\'s government confirmed 15 of its citizens were killed fighting for Russia in Ukraine after being lured by recruitment agents promising lucrative jobs. Harare says it is engaging Moscow to repatriate bodies and bring home survivors, exposing a disturbing pattern of African labor trafficking into war zones.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'conflict',
    country: 'Zimbabwe',
    countryCode: 'ZW',
    lat: -17.8252,
    lng: 31.0335,
    publishedAt: '2026-03-26T05:00:00Z',
    url: 'https://www.bbc.com/news/articles/clyxevz45x9o',
    bsScore: 86,
    biasAnalysis: 'Reports official government statements; highlights human trafficking angle of Russia\'s foreign recruitment.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260326-am-008',
    title: 'Philippines Transport Workers Strike Over Fuel Costs as Iran War Bites',
    summary: 'Transport workers across the Philippines staged protests over surging fuel costs linked to the Iran war and Strait of Hormuz blockade. The strike comes as a ship carrying Russian crude arrived in Manila, underscoring how the Middle East conflict is forcing nations to seek alternative energy suppliers at premium prices.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'economy',
    country: 'Philippines',
    countryCode: 'PH',
    lat: 14.5995,
    lng: 120.9842,
    publishedAt: '2026-03-26T04:30:00Z',
    url: 'https://www.bbc.com/news/articles/c4glxn24gd6o',
    bsScore: 85,
    biasAnalysis: 'Connects local labor action to global energy crisis; factual reporting on economic ripple effects.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260326-am-009',
    title: 'Mark Carney Rebukes Air Canada Chief Over English-Only Crash Message',
    summary: 'Canadian Prime Minister Mark Carney criticized Air Canada\'s CEO for issuing a condolence video in English only after the fatal LaGuardia crash, reviving long-standing tensions over linguistic rights. Two pilots died when an Air Canada plane collided with a firefighting vehicle in New York, with nine still hospitalized.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'politics',
    country: 'Canada',
    countryCode: 'CA',
    lat: 45.4215,
    lng: -75.6972,
    publishedAt: '2026-03-26T08:30:00Z',
    url: 'https://www.theguardian.com/world/2026/mar/26/mark-carney-air-canada-laguardia-crash',
    bsScore: 88,
    biasAnalysis: 'Frames story through bilingualism politics but includes factual crash reporting and official statements.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'sweep-20260326-am-010',
    title: 'Australia Growth Forecasts Slashed as Global Economy Faces Inflation Spike',
    summary: 'The OECD has slashed Australian growth forecasts, warning the Middle East war will test global resilience with Australia expected to suffer from higher interest rates and inflation. The report predicts the Iran conflict could push the world economy toward stagflation as energy prices remain elevated through 2026.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'economy',
    country: 'Australia',
    countryCode: 'AU',
    lat: -33.8688,
    lng: 151.2093,
    publishedAt: '2026-03-26T07:00:00Z',
    url: 'https://www.theguardian.com/world/2026/mar/26/australia-growth-forecasts-slashed-oecd-iran-war',
    bsScore: 89,
    biasAnalysis: 'Economic analysis based on OECD institutional data; appropriately cautious about stagflation predictions.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260326-am-011',
    title: 'Two Drone Strikes on Civilian Targets Kill 28 People in Sudan',
    summary: 'Sudan\'s army launched drone strikes on a market in North Darfur and a truck carrying civilians in North Kordofan, killing at least 28 people as the civil war approaches its fourth year. The attacks mark an escalation in the targeting of civilian infrastructure by both warring factions.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'conflict',
    country: 'Sudan',
    countryCode: 'SD',
    lat: 11.7500,
    lng: 26.0500,
    publishedAt: '2026-03-26T06:00:00Z',
    url: 'https://www.theguardian.com/world/2026/mar/26/sudan-drone-strikes-civilian-targets',
    bsScore: 82,
    biasAnalysis: 'Humanitarian-focused reporting on under-covered conflict; emphasizes civilian casualties.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'sweep-20260326-am-012',
    title: 'Taliban Release US Academic Held in Detention for Over a Year',
    summary: 'The Taliban has released Dennis Coyle, a US academic detained in January 2025 for violating unspecified laws. Secretary of State Marco Rubio welcomed the release, which comes amid ongoing tensions between Washington and Kabul despite the US withdrawal from Afghanistan.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'politics',
    country: 'Afghanistan',
    countryCode: 'AF',
    lat: 34.5553,
    lng: 69.2075,
    publishedAt: '2026-03-26T05:00:00Z',
    url: 'https://www.theguardian.com/world/2026/mar/26/taliban-release-us-academic-dennis-coyle',
    bsScore: 86,
    biasAnalysis: 'Diplomatic reporting with limited details on detention circumstances; appropriately cautious on backstory.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'sweep-20260326-am-013',
    title: 'Growing US Military Presence Around Iran Suggests Potential Ground Operations',
    summary: 'Military analysts note the growing US troop presence around Iran suggests a possible shift from air campaign to ground operations. The Pentagon has deployed additional assets to Gulf states as the war enters its fourth week with no diplomatic breakthrough in sight.',
    source: 'Al Jazeera',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'conflict',
    country: 'United States',
    countryCode: 'US',
    lat: 38.9072,
    lng: -77.0369,
    publishedAt: '2026-03-25T22:00:00Z',
    url: 'https://www.aljazeera.com/news/2026/3/25/war-on-iran-what-troops-is-the-us-moving-to-the-gulf',
    bsScore: 72,
    biasAnalysis: 'Analysis piece based on military observation; speculative about ground operations without official confirmation.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'sweep-20260326-am-014',
    title: 'EU Advances Trade Deal with US Despite Trump Tariff Uncertainty',
    summary: 'The European Union backed a trade deal with the United States after months of delays caused by uncertainty over the legality of Trump\'s tariff regime. The agreement includes safeguards designed to protect EU industries from sudden US trade policy shifts.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'economy',
    country: 'Belgium',
    countryCode: 'BE',
    lat: 50.8503,
    lng: 4.3517,
    publishedAt: '2026-03-26T09:00:00Z',
    url: 'https://www.theguardian.com/world/live/2026/mar/26/eu-us-trade-deal',
    bsScore: 84,
    biasAnalysis: 'Trade reporting from EU perspective; emphasizes safeguards against US policy volatility.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'sweep-20260326-am-015',
    title: 'US Has Caused $10 Trillion in Climate Damage Since 1990, Research Finds',
    summary: 'New research estimates the United States has caused $10 trillion worth of climate damage since 1990 through carbon emissions, dwarfing other nations\' contributions. The study provides a quantitative basis for ongoing debates about climate reparations and historical responsibility.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'climate',
    country: 'United States',
    countryCode: 'US',
    lat: 38.9072,
    lng: -77.0369,
    publishedAt: '2026-03-26T06:00:00Z',
    url: 'https://www.theguardian.com/environment/2026/mar/26/us-climate-damage-10-trillion',
    bsScore: 78,
    biasAnalysis: 'Report-based coverage with methodology caveats; editorial framing emphasizes US accountability.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'sweep-20260326-am-016',
    title: 'Philippines Declares National Energy Emergency as Iran War Grinds On',
    summary: 'The Philippines government has declared a national energy emergency and boosted coal power generation as the Iran war disrupts global fuel supplies. The archipelago nation joins a growing list of countries reverting to fossil fuels as the energy crisis forces pragmatic choices over climate commitments.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'climate',
    country: 'Philippines',
    countryCode: 'PH',
    lat: 14.5995,
    lng: 120.9842,
    publishedAt: '2026-03-26T03:00:00Z',
    url: 'https://www.theguardian.com/world/2026/mar/26/philippines-energy-emergency-iran-war',
    bsScore: 83,
    biasAnalysis: 'Environmental reporting highlighting tension between energy security and climate goals during crisis.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'sweep-20260326-am-017',
    title: 'Epstein Survivor Speaks Out: \'I Have No Recollection of Anything\' After Being Drugged',
    summary: 'A woman who says she was drugged and raped by Jeffrey Epstein has spoken publicly for the first time to BBC Newsnight. She described being given water after a massage at Epstein\'s Palm Beach mansion and blacking out for 12 hours, later discovering signs she had been assaulted while unconscious.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'culture',
    country: 'United States',
    countryCode: 'US',
    lat: 26.7153,
    lng: -80.0534,
    publishedAt: '2026-03-26T02:00:00Z',
    url: 'https://www.bbc.com/news/articles/c05dz39m6qgo',
    bsScore: 88,
    biasAnalysis: 'First-person survivor testimony with appropriate content warnings; journalistically handled sensitive subject.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'sweep-20260326-am-018',
    title: 'Jailed Bolsonaro Granted Humanitarian House Arrest Amid Failing Health',
    summary: 'Brazil\'s former president Jair Bolsonaro has been granted house arrest on humanitarian grounds as his health deteriorates while serving a prison sentence. The far-right leader was jailed following his conviction for plotting to overturn the 2022 election results.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'politics',
    country: 'Brazil',
    countryCode: 'BR',
    lat: -15.7975,
    lng: -47.8919,
    publishedAt: '2026-03-26T01:00:00Z',
    url: 'https://www.theguardian.com/world/2026/mar/26/bolsonaro-house-arrest-health',
    bsScore: 85,
    biasAnalysis: 'Straightforward legal reporting; provides context on Bolsonaro\'s conviction for election subversion.',
    credibilityTier: 2,
    isBreaking: false,
  },
  // RETAINED RELEVANT ARTICLES FROM PREVIOUS SWEEP
  {
    id: 'sweep-20260323-001',
    title: 'Trump Postpones Strikes on Iran Power Plants, Claims "Productive" Talks',
    summary: 'President Trump announced a five-day postponement of planned strikes on Iranian power plants, claiming productive discussions with Tehran. However, Iran\'s parliament speaker flatly denied any talks took place, calling the claims "fake news" and saying the US is trying to "escape the quagmire."',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'conflict',
    country: 'United States',
    countryCode: 'US',
    lat: 38.9072,
    lng: -77.0369,
    publishedAt: '2026-03-23T18:00:00Z',
    url: 'https://www.bbc.com/news/live/ce35wke27ynt',
    bsScore: 82,
    biasAnalysis: 'BBC provides balanced coverage presenting both US and Iranian positions with appropriate skepticism.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260323-006',
    title: 'IEA Chief: Iran War Energy Crunch Worse Than 1970s Oil Crises',
    summary: 'The International Energy Agency chief warned that the energy disruption caused by the Iran conflict is more severe than both the 1970s oil crises and the Ukraine war combined. IEA members agreed to release 400 million barrels from strategic reserves to stabilize markets.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'economy',
    country: 'France',
    countryCode: 'FR',
    lat: 48.8566,
    lng: 2.3522,
    publishedAt: '2026-03-23T13:00:00Z',
    url: 'https://www.theguardian.com/world/live/2026/mar/23/middle-east-crisis-live-iea-chief-says-iran-war-energy-crunch-worse-than-1970s-oil-crises',
    bsScore: 88,
    biasAnalysis: 'Reporting relies on IEA institutional analysis with factual framing of energy market implications.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260323-008',
    title: 'Strike on Sudan Hospital Kills at Least 64, WHO Reports',
    summary: 'An army drone attack on a health facility in East Darfur killed at least 64 people and wounded 89 more, according to the WHO. Victims included children and medical personnel. The strike has been widely condemned by international humanitarian organizations.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'conflict',
    country: 'Sudan',
    countryCode: 'SD',
    lat: 11.7500,
    lng: 26.0500,
    publishedAt: '2026-03-23T10:00:00Z',
    url: 'https://www.theguardian.com/world/2026/mar/23/strike-sudan-hospital-kills-who',
    bsScore: 90,
    biasAnalysis: 'Reporting based on WHO official data with emphasis on civilian casualties and international law violations.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260323-011',
    title: 'Italian Voters Reject Meloni\'s Plan to Overhaul Judiciary in Referendum',
    summary: 'Italian voters decisively rejected Prime Minister Giorgia Meloni\'s constitutional referendum to reform the judiciary, dealing a significant blow to her governing coalition. The results showed clear opposition to concentrating judicial appointment powers in the executive.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'politics',
    country: 'Italy',
    countryCode: 'IT',
    lat: 41.9028,
    lng: 12.4964,
    publishedAt: '2026-03-23T20:00:00Z',
    url: 'https://www.theguardian.com/world/2026/mar/23/italy-voters-reject-overhaul-judiciary-giorgia-meloni',
    bsScore: 92,
    biasAnalysis: 'Straightforward election result reporting with political analysis of implications for Meloni\'s coalition.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'sweep-20260323-017',
    title: 'Two Pilots Killed After Air Canada Jet Collision at LaGuardia Airport',
    summary: 'Two pilots were killed when an Air Canada plane carrying 72 passengers collided with a firefighting vehicle on the runway at LaGuardia Airport in New York. Nine people remain hospitalized. The NTSB has launched an investigation into the fatal incident.',
    source: 'BBC News',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'politics',
    country: 'United States',
    countryCode: 'US',
    lat: 40.7769,
    lng: -73.8740,
    publishedAt: '2026-03-23T22:00:00Z',
    url: 'https://www.bbc.com/news/articles/c78rdze8zvjo',
    bsScore: 95,
    biasAnalysis: 'Straightforward factual reporting of the aviation incident with official sources and witness accounts.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'sweep-20260323-024',
    title: 'China Has Been Preparing for a Global Energy Crisis for Years. It Is Paying Off Now',
    summary: 'As the Iran war drives global energy prices to crisis levels, China\'s years of strategic investment in domestic renewable energy, nuclear power, and strategic petroleum reserves are insulating it from the worst supply shocks hitting Western economies.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'economy',
    country: 'China',
    countryCode: 'CN',
    lat: 39.9042,
    lng: 116.4074,
    publishedAt: '2026-03-23T08:30:00Z',
    url: 'https://www.theguardian.com/world/2026/mar/23/china-energy-crisis-preparation',
    bsScore: 80,
    biasAnalysis: 'Analysis piece examining Chinese energy strategy with implicit criticism of Western unpreparedness.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'sweep-20260323-026',
    title: 'Amazon Leo Satellite Internet Ramps Up Launches to Rival Starlink',
    summary: 'Amazon\'s satellite internet initiative Amazon Leo announced it is on track to more than double its annual launch rate with over 20 missions planned. The company has deployed more than 200 satellites so far, with the next mission set for March 29th.',
    source: 'The Verge',
    sourceReliability: 4,
    sourceBias: -0.1,
    category: 'tech',
    country: 'United States',
    countryCode: 'US',
    lat: 47.6062,
    lng: -122.3321,
    publishedAt: '2026-03-23T21:00:00Z',
    url: 'https://www.theverge.com/news/amazon-leo-satellite-launches',
    bsScore: 88,
    biasAnalysis: 'Tech industry reporting with factual coverage of Amazon\'s space ambitions and competitive positioning.',
    credibilityTier: 3,
    isBreaking: false,
  },
  {
    id: 'uk-001',
    title: 'Bank of England Holds Rates Amid Stagflation Fears',
    summary: 'The Bank of England kept its base rate at 5.25% in a split vote, with two members pushing for cuts as GDP growth stalls at 0.1%. Governor Bailey warned that persistent services inflation remains the primary obstacle to easing.',
    source: 'The Economist',
    sourceReliability: 5,
    sourceBias: 0.1,
    category: 'economy',
    country: 'United Kingdom',
    countryCode: 'GB',
    lat: 51.5074,
    lng: -0.1278,
    publishedAt: '2026-03-21T10:00:00Z',
    url: 'https://example.com/article/uk-001',
    bsScore: 93,
    biasAnalysis: 'The Economist provides rigorous economic analysis with classical liberal framing.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'eu-001',
    title: 'EU Passes Landmark AI Liability Directive',
    summary: 'The European Parliament voted 421-132 to approve the AI Liability Directive, establishing that companies deploying AI systems bear responsibility for damages caused by their products. The directive creates a presumption of causation when AI systems cause harm.',
    source: 'Politico Europe',
    sourceReliability: 4,
    sourceBias: 0.0,
    category: 'tech',
    country: 'Belgium',
    countryCode: 'BE',
    lat: 50.8503,
    lng: 4.3517,
    publishedAt: '2026-03-21T14:30:00Z',
    url: 'https://example.com/article/eu-001',
    bsScore: 91,
    biasAnalysis: 'Politico Europe provides detailed legislative reporting with balanced stakeholder perspectives.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'jp-001',
    title: 'Japan Central Bank Raises Interest Rates to 0.75%, Highest Since 2008',
    summary: 'The Bank of Japan raised its policy rate by 25 basis points to 0.75%, the highest level since 2008, citing sustained wage growth and inflationary pressures. Governor Ueda signaled further hikes are possible, marking a shift away from decades of ultra-loose monetary policy.',
    source: 'Nikkei Asia',
    sourceReliability: 5,
    sourceBias: 0.1,
    category: 'economy',
    country: 'Japan',
    countryCode: 'JP',
    lat: 35.6762,
    lng: 139.6503,
    publishedAt: '2026-03-20T06:00:00Z',
    url: 'https://example.com/article/jp-001',
    bsScore: 95,
    biasAnalysis: 'Nikkei Asia provides authoritative coverage of BOJ policy with deep institutional knowledge.',
    credibilityTier: 1,
    isBreaking: false,
  },
];
