import { Article } from './types';

// Seed data for SITREP - Part 6: Western, European & Asian sources (Articles 53-72)
export const articlesPart6: Article[] = [
  // UK / WESTERN
  {
    id: 'uk-001',
    title: 'Bank of England Holds Rates Amid Stagflation Fears',
    summary: 'The Bank of England kept its base rate at 5.25% in a split vote, with two members pushing for cuts as GDP growth stalls at 0.1%. Governor Bailey warned that persistent services inflation remains the primary obstacle to easing, while business groups say high rates are strangling investment.',
    source: 'The Economist',
    sourceReliability: 5,
    sourceBias: 0.1,
    category: 'economy',
    country: 'United Kingdom',
    countryCode: 'GB',
    lat: 51.5074,
    lng: -0.1278,
    publishedAt: '2026-03-21T10:00:00Z',
    url: 'https://example.com/article/uk-001',
    bsScore: 93,
    biasAnalysis: 'The Economist provides rigorous economic analysis with classical liberal framing.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'uk-002',
    title: 'NHS Waiting Lists Hit 8 Million as Junior Doctor Strikes Resume',
    summary: 'The number of patients waiting for treatment in England has reached a new record of 8.1 million. Junior doctors began a five-day walkout over pay and conditions, marking the fourteenth round of strikes since 2023. The government accused the BMA of holding patients hostage, while doctors argue real-terms pay has fallen 26% since 2008.',
    source: 'The Times',
    sourceReliability: 4,
    sourceBias: 0.2,
    category: 'politics',
    country: 'United Kingdom',
    countryCode: 'GB',
    lat: 51.5074,
    lng: -0.1278,
    publishedAt: '2026-03-20T07:00:00Z',
    url: 'https://example.com/article/uk-002',
    bsScore: 84,
    biasAnalysis: 'The Times provides factual reporting with center-right editorial perspective on public sector disputes.',
    credibilityTier: 2,
    isBreaking: true,
  },
  {
    id: 'uk-003',
    title: 'UK Government Introduces Online Safety Act Enforcement Powers',
    summary: 'Ofcom gained new powers to fine tech platforms up to 10% of global revenue for failing to protect children online. The enforcement framework covers content moderation, age verification, and algorithmic transparency requirements. Meta and X have signaled legal challenges.',
    source: 'The Telegraph',
    sourceReliability: 4,
    sourceBias: 0.4,
    category: 'tech',
    country: 'United Kingdom',
    countryCode: 'GB',
    lat: 51.5074,
    lng: -0.1278,
    publishedAt: '2026-03-19T14:00:00Z',
    url: 'https://example.com/article/uk-003',
    bsScore: 80,
    biasAnalysis: 'The Telegraph leans conservative but provides substantive technology policy coverage.',
    credibilityTier: 2,
    isBreaking: false,
  },

  // CANADA
  {
    id: 'can-001',
    title: 'Canada Announces $4.5 Billion Critical Minerals Strategy to Counter China',
    summary: 'Ottawa unveiled a comprehensive plan to accelerate mining and processing of lithium, cobalt, and rare earths, positioning Canada as an alternative supplier to China for Western allies. The strategy includes fast-tracked environmental reviews and Indigenous partnership agreements, drawing both praise from industry and criticism from environmental groups.',
    source: 'The Globe and Mail',
    sourceReliability: 4,
    sourceBias: 0.1,
    category: 'economy',
    country: 'Canada',
    countryCode: 'CA',
    lat: 45.4215,
    lng: -75.6972,
    publishedAt: '2026-03-20T12:00:00Z',
    url: 'https://example.com/article/can-001',
    bsScore: 86,
    biasAnalysis: 'The Globe and Mail provides balanced business-focused reporting with slight center-right framing.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'can-002',
    title: 'Toronto Housing Market Sees First Price Decline in Three Years',
    summary: 'Average home prices in the Greater Toronto Area fell 4.2% year over year to $1.02 million, the first annual decline since 2023. Economists attribute the shift to high interest rates, stricter mortgage rules, and increased supply from completed condo developments. First-time buyers remain cautious despite the correction.',
    source: 'CBC News',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'economy',
    country: 'Canada',
    countryCode: 'CA',
    lat: 43.6532,
    lng: -79.3832,
    publishedAt: '2026-03-19T09:00:00Z',
    url: 'https://example.com/article/can-002',
    bsScore: 85,
    biasAnalysis: 'CBC provides factual economic reporting with attention to affordability impacts.',
    credibilityTier: 1,
    isBreaking: false,
  },

  // EUROPE
  {
    id: 'eur-003',
    title: 'Italy Tightens Immigration Policy, Deploys Navy to Mediterranean',
    summary: 'Prime Minister Meloni authorized naval operations to intercept migrant boats further from Italian shores, a move that human rights organizations say violates international maritime law. Italy processed 145,000 asylum claims last year, a 50% increase that has strained reception centers and fueled political debate.',
    source: 'Corriere della Sera',
    sourceReliability: 4,
    sourceBias: 0.1,
    category: 'politics',
    country: 'Italy',
    countryCode: 'IT',
    lat: 41.9028,
    lng: 12.4964,
    publishedAt: '2026-03-20T11:00:00Z',
    url: 'https://example.com/article/eur-003',
    bsScore: 79,
    biasAnalysis: 'Corriere della Sera provides mainstream Italian perspective with measured editorial tone.',
    credibilityTier: 2,
    isBreaking: false,
    originalLanguage: 'it',
  },
  {
    id: 'eur-004',
    title: 'Switzerland Votes to Ban New Fossil Fuel Heating Installations',
    summary: 'Swiss voters approved a referendum mandating that all new heating systems must use renewable energy sources starting 2027. The measure passed with 58% support, driven by urban cantons, while rural areas voted against. The building sector accounts for a quarter of Switzerland\'s carbon emissions.',
    source: 'Neue Zuercher Zeitung',
    sourceReliability: 5,
    sourceBias: 0.1,
    category: 'climate',
    country: 'Switzerland',
    countryCode: 'CH',
    lat: 46.9481,
    lng: 7.4474,
    publishedAt: '2026-03-19T15:00:00Z',
    url: 'https://example.com/article/eur-004',
    bsScore: 90,
    biasAnalysis: 'NZZ provides rigorous analysis with liberal-conservative perspective typical of Swiss quality press.',
    credibilityTier: 1,
    isBreaking: false,
    originalLanguage: 'de',
  },
  {
    id: 'eur-005',
    title: 'Finland Accelerates NATO Integration with Largest Nordic Military Exercise',
    summary: 'Finland hosted 20,000 troops from 13 NATO allies in Arctic Shield 2026, the largest military exercise in the Nordic region since the Cold War. The drills simulated defense of Finland\'s 1,340-kilometer border with Russia and tested rapid reinforcement corridors from Norway and Sweden.',
    source: 'Helsingin Sanomat',
    sourceReliability: 4,
    sourceBias: -0.1,
    category: 'conflict',
    country: 'Finland',
    countryCode: 'FI',
    lat: 60.1699,
    lng: 24.9384,
    publishedAt: '2026-03-18T08:00:00Z',
    url: 'https://example.com/article/eur-005',
    bsScore: 87,
    biasAnalysis: 'Helsingin Sanomat provides factual defense reporting as Finland\'s paper of record.',
    credibilityTier: 2,
    isBreaking: false,
    originalLanguage: 'fi',
  },
  {
    id: 'eur-006',
    title: 'Poland Becomes Europe\'s Fastest Growing Economy at 4.1% GDP Growth',
    summary: 'Poland recorded 4.1% GDP growth in Q4 2025, the highest in the EU, driven by consumer spending, EU cohesion funds, and a booming tech sector. Warsaw has emerged as a major European tech hub, attracting talent from Ukraine and the Baltics. However, labor shortages and infrastructure bottlenecks threaten to cap growth.',
    source: 'Politico Europe',
    sourceReliability: 4,
    sourceBias: -0.1,
    category: 'economy',
    country: 'Poland',
    countryCode: 'PL',
    lat: 52.2297,
    lng: 21.0122,
    publishedAt: '2026-03-17T10:30:00Z',
    url: 'https://example.com/article/eur-006',
    bsScore: 85,
    biasAnalysis: 'Politico Europe provides data-driven economic reporting with EU institutional perspective.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'eur-007',
    title: 'Ireland Becomes First EU Country to Recognize Palestinian Statehood',
    summary: 'The Dail voted 121 to 27 to formally recognize the State of Palestine, making Ireland the first EU member to do so unilaterally. Taoiseach Harris called it a moral imperative, while Israel recalled its ambassador from Dublin. Spain and Norway are expected to follow within weeks.',
    source: 'The Irish Times',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'politics',
    country: 'Ireland',
    countryCode: 'IE',
    lat: 53.3498,
    lng: -6.2603,
    publishedAt: '2026-03-16T13:00:00Z',
    url: 'https://example.com/article/eur-007',
    bsScore: 84,
    biasAnalysis: 'The Irish Times provides balanced political reporting as Ireland\'s paper of record.',
    credibilityTier: 2,
    isBreaking: true,
  },
  {
    id: 'eur-008',
    title: 'Denmark Leads European Push for Offshore Wind Mega-Projects',
    summary: 'Copenhagen approved construction of two energy islands capable of generating 10GW of offshore wind power, enough to supply 10 million European households. The $35 billion project involves partnerships with Germany and the Netherlands and is the centerpiece of the EU\'s plan to triple offshore wind capacity by 2030.',
    source: 'Politiken',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'climate',
    country: 'Denmark',
    countryCode: 'DK',
    lat: 55.6761,
    lng: 12.5683,
    publishedAt: '2026-03-15T09:00:00Z',
    url: 'https://example.com/article/eur-008',
    bsScore: 83,
    biasAnalysis: 'Politiken provides quality reporting with social-liberal editorial perspective.',
    credibilityTier: 2,
    isBreaking: false,
    originalLanguage: 'da',
  },

  // ASIA
  {
    id: 'asia-001',
    title: 'Singapore Launches $1 Billion National AI Strategy 2.0',
    summary: 'Prime Minister Wong unveiled an expanded national AI plan targeting healthcare, logistics, and financial services. The strategy includes mandatory AI ethics guidelines for government procurement, a sovereign compute cluster, and visa fast-tracks for AI researchers. Singapore aims to become the ASEAN hub for trustworthy AI deployment.',
    source: 'The Straits Times',
    sourceReliability: 4,
    sourceBias: 0.1,
    category: 'tech',
    country: 'Singapore',
    countryCode: 'SG',
    lat: 1.3521,
    lng: 103.8198,
    publishedAt: '2026-03-21T06:00:00Z',
    url: 'https://example.com/article/asia-001',
    bsScore: 82,
    biasAnalysis: 'The Straits Times provides factual reporting with generally pro-government framing on national strategy.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'asia-002',
    title: 'Thailand Canal Project Gains Momentum as China Pledges $28 Billion',
    summary: 'Beijing offered to finance the long-proposed Kra Canal that would cut across southern Thailand, bypassing the Strait of Malacca and reshaping Asian shipping routes. The project raises strategic concerns for Singapore and Malaysia while offering Thailand massive economic potential. Environmental groups warn of catastrophic mangrove destruction.',
    source: 'Bangkok Post',
    sourceReliability: 3,
    sourceBias: 0,
    category: 'economy',
    country: 'Thailand',
    countryCode: 'TH',
    lat: 7.8804,
    lng: 98.3923,
    publishedAt: '2026-03-20T04:30:00Z',
    url: 'https://example.com/article/asia-002',
    bsScore: 74,
    biasAnalysis: 'Bangkok Post provides English-language Thai coverage with generally balanced perspective.',
    credibilityTier: 3,
    isBreaking: false,
  },
  {
    id: 'asia-003',
    title: 'India Overtakes Japan as World\'s Fourth Largest Economy',
    summary: 'IMF data confirms India\'s nominal GDP reached $4.3 trillion, surpassing Japan and trailing only the US, China, and Germany. The milestone reflects India\'s rapid services-driven growth, though GDP per capita remains at $3,000, well below peer nations. The rupee strengthened 1.2% on the announcement.',
    source: 'Times of India',
    sourceReliability: 3,
    sourceBias: 0.1,
    category: 'economy',
    country: 'India',
    countryCode: 'IN',
    lat: 19.076,
    lng: 72.8777,
    publishedAt: '2026-03-19T05:00:00Z',
    url: 'https://example.com/article/asia-003',
    bsScore: 78,
    biasAnalysis: 'Times of India covers economic milestones with national pride framing and adequate data sourcing.',
    credibilityTier: 3,
    isBreaking: true,
  },
  {
    id: 'asia-004',
    title: 'South Korea and Japan Agree to Joint Semiconductor Supply Chain',
    summary: 'In a historic shift, Seoul and Tokyo announced a bilateral agreement to coordinate semiconductor production and research, setting aside long-standing trade disputes. The deal covers memory chip manufacturing, advanced packaging, and joint R&D facilities, responding to US pressure for allied tech cooperation against China.',
    source: 'Yonhap News Agency',
    sourceReliability: 4,
    sourceBias: 0,
    category: 'tech',
    country: 'South Korea',
    countryCode: 'KR',
    lat: 37.5665,
    lng: 126.978,
    publishedAt: '2026-03-18T07:00:00Z',
    url: 'https://example.com/article/asia-004',
    bsScore: 86,
    biasAnalysis: 'Yonhap provides factual wire-service reporting as South Korea\'s national news agency.',
    credibilityTier: 1,
    isBreaking: false,
    originalLanguage: 'ko',
  },
  {
    id: 'asia-005',
    title: 'Indonesia Bans Nickel Ore Exports, Triggering Global Supply Shock',
    summary: 'Jakarta expanded its mineral export ban to include all grades of nickel ore, extending a policy designed to force foreign companies to process raw materials domestically. The move sent nickel futures up 12% on the London Metal Exchange and threatens EV battery production timelines for Tesla, BYD, and Volkswagen.',
    source: 'Nikkei Asia',
    sourceReliability: 4,
    sourceBias: 0,
    category: 'economy',
    country: 'Indonesia',
    countryCode: 'ID',
    lat: -6.2088,
    lng: 106.8456,
    publishedAt: '2026-03-17T03:00:00Z',
    url: 'https://example.com/article/asia-005',
    bsScore: 87,
    biasAnalysis: 'Nikkei Asia provides quality business journalism covering pan-Asian economic developments.',
    credibilityTier: 2,
    isBreaking: true,
  },
  {
    id: 'asia-006',
    title: 'Vietnam Emerges as Top Alternative to China for Electronics Manufacturing',
    summary: 'Vietnam attracted $9.2 billion in foreign direct investment for electronics manufacturing in Q1 2026, led by Samsung, Apple suppliers, and Intel. The country now produces 15% of the world\'s smartphones. However, labor shortages in southern industrial zones and infrastructure gaps in power grid capacity are emerging constraints.',
    source: 'Reuters',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'economy',
    country: 'Vietnam',
    countryCode: 'VN',
    lat: 10.8231,
    lng: 106.6297,
    publishedAt: '2026-03-16T08:00:00Z',
    url: 'https://example.com/article/asia-006',
    bsScore: 89,
    biasAnalysis: 'Reuters provides balanced reporting on Asian investment trends with supply chain analysis.',
    credibilityTier: 1,
    isBreaking: false,
  },

  // AUSTRALIA / OCEANIA
  {
    id: 'oce-001',
    title: 'Australia Commits $3 Billion to Pacific Islands Climate Resilience Fund',
    summary: 'Canberra announced its largest climate aid package for Pacific Island nations, funding seawall construction, desalination plants, and disaster response infrastructure across 14 countries. The initiative is seen as countering China\'s growing influence in the region, which has offered similar infrastructure deals tied to security agreements.',
    source: 'Sydney Morning Herald',
    sourceReliability: 4,
    sourceBias: -0.1,
    category: 'climate',
    country: 'Australia',
    countryCode: 'AU',
    lat: -33.8688,
    lng: 151.2093,
    publishedAt: '2026-03-21T01:00:00Z',
    url: 'https://example.com/article/oce-001',
    bsScore: 83,
    biasAnalysis: 'SMH provides quality reporting on Asia-Pacific geopolitics with center-left editorial position.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'oce-002',
    title: 'New Zealand Central Bank Cuts Rates as Housing Market Cools',
    summary: 'The Reserve Bank of New Zealand reduced the official cash rate by 25 basis points to 4.75%, citing weaker inflation and a cooling property market. Auckland house prices have fallen 18% from their 2021 peak. Economists expect two more cuts this year as the economy adjusts to post-pandemic normalization.',
    source: 'New Zealand Herald',
    sourceReliability: 4,
    sourceBias: 0,
    category: 'economy',
    country: 'New Zealand',
    countryCode: 'NZ',
    lat: -36.8485,
    lng: 174.7633,
    publishedAt: '2026-03-19T22:00:00Z',
    url: 'https://example.com/article/oce-002',
    bsScore: 84,
    biasAnalysis: 'NZ Herald provides balanced economic reporting as the country\'s largest daily.',
    credibilityTier: 2,
    isBreaking: false,
  },
];

export default articlesPart6;
