import { Article } from './types';

// Seed data for SITREP - Part 1: US Politics & Ukraine/Russia (Articles 1-15)
export const articles: Article[] = [
  // US POLITICS - Left leaning sources
  {
    id: 'us-001',
    title: 'Senate Democrats Push for Sweeping Climate Provisions in Infrastructure Bill',
    summary: 'Democratic senators are rallying support for a comprehensive climate package that would allocate $500 billion toward renewable energy infrastructure, electric vehicle charging networks, and green job training programs. The legislation faces stiff opposition from Republicans who argue the costs are unsustainable.',
    source: 'NPR',
    sourceReliability: 4,
    sourceBias: -0.4,
    category: 'politics',
    country: 'United States',
    countryCode: 'US',
    lat: 38.9072,
    lng: -77.0369,
    publishedAt: '2026-03-20T14:30:00Z',
    url: 'https://example.com/article/us-001',
    bsScore: 72,
    biasAnalysis: 'NPR provides balanced coverage with slight progressive framing on climate policy impacts.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'us-002',
    title: 'Labor Unions Gain Momentum as Starbucks Workers Vote to Unionize in Record Numbers',
    summary: 'Workers at over 150 Starbucks locations have voted to unionize in the past month, marking a significant resurgence in organized labor activity. Labor advocates say this reflects growing worker dissatisfaction with wages and conditions, while business groups warn of potential impacts on competitiveness.',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.5,
    category: 'economy',
    country: 'United States',
    countryCode: 'US',
    lat: 40.7128,
    lng: -74.006,
    publishedAt: '2026-03-19T09:15:00Z',
    url: 'https://example.com/article/us-002',
    bsScore: 68,
    biasAnalysis: 'The Guardian presents union perspectives prominently while including some business counterpoints.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'us-003',
    title: 'Biden Administration Announces Student Loan Forgiveness Expansion',
    summary: 'The Department of Education unveiled a new pathway for student debt relief targeting borrowers who have been paying for over 20 years. The plan could affect approximately 3 million Americans and represents the administrations latest attempt to address the student debt crisis after Supreme Court setbacks.',
    source: 'New York Times',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'politics',
    country: 'United States',
    countryCode: 'US',
    lat: 38.9072,
    lng: -77.0369,
    publishedAt: '2026-03-21T11:00:00Z',
    url: 'https://example.com/article/us-003',
    bsScore: 75,
    biasAnalysis: 'NYT provides factual reporting with center-left contextual framing on policy implications.',
    credibilityTier: 2,
    isBreaking: true,
  },
  {
    id: 'us-004',
    title: 'Progressive Caucus Calls for Medicare for All Vote After Insurance Premium Spike',
    source: 'The Intercept',
    sourceReliability: 3,
    sourceBias: -0.7,
    category: 'politics',
    country: 'United States',
    countryCode: 'US',
    lat: 38.9072,
    lng: -77.0369,
    publishedAt: '2026-03-18T16:45:00Z',
    url: 'https://example.com/article/us-004',
    summary: 'The Congressional Progressive Caucus is demanding a floor vote on Medicare for All legislation following reports that health insurance premiums will rise an average of 15% next year. The move is seen as largely symbolic given Republican control of the House.',
    bsScore: 65,
    biasAnalysis: 'The Intercept strongly advocates for progressive policy positions with limited conservative perspective.',
    credibilityTier: 3,
    isBreaking: false,
  },
  {
    id: 'us-005',
    title: 'California Enacts Nation\'s Strictest AI Safety Regulations',
    source: 'Reuters',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'tech',
    country: 'United States',
    countryCode: 'US',
    lat: 34.0522,
    lng: -118.2437,
    publishedAt: '2026-03-20T08:30:00Z',
    url: 'https://example.com/article/us-005',
    summary: 'California Governor signed landmark legislation requiring AI companies to conduct safety audits and implement kill switches for systems above certain capability thresholds. Tech industry groups have criticized the law as stifling innovation.',
    bsScore: 88,
    biasAnalysis: 'Reuters provides balanced, fact-based reporting with quotes from both supporters and critics.',
    credibilityTier: 1,
    isBreaking: false,
  },

  // US POLITICS - Right leaning sources
  {
    id: 'us-006',
    title: 'Republicans Slam \'Reckless Spending\' as National Debt Hits $38 Trillion',
    source: 'Fox News',
    sourceReliability: 3,
    sourceBias: 0.7,
    category: 'politics',
    country: 'United States',
    countryCode: 'US',
    lat: 38.9072,
    lng: -77.0369,
    publishedAt: '2026-03-20T13:20:00Z',
    url: 'https://example.com/article/us-006',
    summary: 'House Republicans are demanding spending cuts as the national debt reaches unprecedented levels. Speaker Johnson called the trajectory "generational theft" and threatened to withhold support for upcoming appropriations bills without concessions.',
    bsScore: 58,
    biasAnalysis: 'Fox News emphasizes conservative fiscal concerns with selective presentation of economic context.',
    credibilityTier: 3,
    isBreaking: false,
  },
  {
    id: 'us-007',
    title: 'Border Patrol Encounters Surge to Record Highs in Southwest Sectors',
    source: 'Wall Street Journal',
    sourceReliability: 4,
    sourceBias: 0.3,
    category: 'politics',
    country: 'United States',
    countryCode: 'US',
    lat: 25.9014,
    lng: -97.4975,
    publishedAt: '2026-03-19T10:00:00Z',
    url: 'https://example.com/article/us-007',
    summary: 'Border crossings along the southern border reached their highest levels in two decades according to internal CBP data obtained by the Journal. The figures come as immigration remains a top issue for voters heading into midterm elections.',
    bsScore: 82,
    biasAnalysis: 'WSJ provides factual reporting with business-oriented framing on immigration impacts.',
    credibilityTier: 2,
    isBreaking: true,
  },
  {
    id: 'us-008',
    title: 'Second Amendment Advocates Challenge New Federal Gun Storage Requirements',
    source: 'Breitbart',
    sourceReliability: 2,
    sourceBias: 0.9,
    category: 'politics',
    country: 'United States',
    countryCode: 'US',
    lat: 30.2672,
    lng: -97.7431,
    publishedAt: '2026-03-18T14:10:00Z',
    url: 'https://example.com/article/us-008',
    summary: 'Gun rights groups have filed multiple lawsuits challenging new ATF rules requiring safe storage of firearms in homes with children. Critics call the regulations government overreach that criminalizes responsible gun owners.',
    bsScore: 45,
    biasAnalysis: 'Breitbart presents a strong pro-gun perspective with limited consideration of opposing viewpoints.',
    credibilityTier: 4,
    isBreaking: false,
  },
  {
    id: 'us-009',
    title: 'Tax Cut Package Passes House Along Party Lines',
    source: 'National Review',
    sourceReliability: 3,
    sourceBias: 0.8,
    category: 'economy',
    country: 'United States',
    countryCode: 'US',
    lat: 38.9072,
    lng: -77.0369,
    publishedAt: '2026-03-17T16:30:00Z',
    url: 'https://example.com/article/us-009',
    summary: 'House Republicans passed a comprehensive tax reduction package that includes lower corporate rates and expanded individual deductions. The bill faces an uncertain path in the Senate where Democrats have vowed to filibuster.',
    bsScore: 62,
    biasAnalysis: 'National Review emphasizes conservative economic arguments with celebratory tone on tax cuts.',
    credibilityTier: 3,
    isBreaking: false,
  },
  {
    id: 'us-010',
    title: 'Energy Independence Push Gains Steam as Oil Prices Climb',
    source: 'Fox Business',
    sourceReliability: 3,
    sourceBias: 0.6,
    category: 'economy',
    country: 'United States',
    countryCode: 'US',
    lat: 29.7604,
    lng: -95.3698,
    publishedAt: '2026-03-21T09:45:00Z',
    url: 'https://example.com/article/us-010',
    summary: 'Lawmakers from oil-producing states are calling for expanded drilling permits as crude prices hit $95 per barrel. The push comes amid geopolitical tensions affecting global supply chains and renewed debate over domestic production.',
    bsScore: 55,
    biasAnalysis: 'Fox Business emphasizes fossil fuel industry perspectives with limited environmental counterpoints.',
    credibilityTier: 3,
    isBreaking: false,
  },

  // UKRAINE/RUSSIA CONFLICT
  {
    id: 'ukr-001',
    title: 'Ukrainian Forces Strike Russian Naval Base in Black Sea',
    source: 'BBC',
    sourceReliability: 4,
    sourceBias: -0.1,
    category: 'conflict',
    country: 'Ukraine',
    countryCode: 'UA',
    lat: 44.6167,
    lng: 33.5254,
    publishedAt: '2026-03-20T06:00:00Z',
    url: 'https://example.com/article/ukr-001',
    summary: 'Ukrainian naval drones targeted a Russian logistics hub in occupied Crimea, causing significant damage to port infrastructure according to military sources. Russia confirmed "repelling" the attack but acknowledged fires near Sevastopol.',
    bsScore: 85,
    biasAnalysis: 'BBC provides measured reporting with verification of claims from both sides where possible.',
    credibilityTier: 1,
    isBreaking: true,
  },
  {
    id: 'ukr-002',
    title: 'EU Approves €50 Billion Ukraine Aid Package After Hungary Drops Veto',
    source: 'Financial Times',
    sourceReliability: 5,
    sourceBias: -0.1,
    category: 'conflict',
    country: 'Belgium',
    countryCode: 'BE',
    lat: 50.8503,
    lng: 4.3517,
    publishedAt: '2026-03-19T12:00:00Z',
    url: 'https://example.com/article/ukr-002',
    summary: 'European Union leaders unanimously approved a long-stalled financial support package for Ukraine after securing concessions from Hungary. The funding will support Ukrainian government operations and reconstruction efforts through 2027.',
    bsScore: 92,
    biasAnalysis: 'FT provides detailed, factual reporting on institutional processes with minimal bias.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'ukr-003',
    title: 'Russian Missile Strikes Hit Civilian Infrastructure in Kharkiv',
    source: 'Associated Press',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'conflict',
    country: 'Ukraine',
    countryCode: 'UA',
    lat: 49.9935,
    lng: 36.2304,
    publishedAt: '2026-03-21T07:30:00Z',
    url: 'https://example.com/article/ukr-003',
    summary: 'Overnight missile attacks damaged residential buildings and a hospital in Kharkiv, local officials reported. At least 12 civilians were killed and dozens injured in what Ukraine described as a deliberate targeting of civilian areas.',
    bsScore: 90,
    biasAnalysis: 'AP provides factual reporting with verification of casualty figures through multiple sources.',
    credibilityTier: 1,
    isBreaking: true,
  },
  {
    id: 'ukr-004',
    title: 'Moscow Accuses West of \'Proxy War\' as NATO Expands Arms Shipments',
    source: 'Al Jazeera',
    sourceReliability: 3,
    sourceBias: -0.2,
    category: 'conflict',
    country: 'Russia',
    countryCode: 'RU',
    lat: 55.7558,
    lng: 37.6173,
    publishedAt: '2026-03-18T11:00:00Z',
    url: 'https://example.com/article/ukr-004',
    summary: 'Russian Foreign Ministry spokesperson accused NATO members of direct involvement in the conflict following announcements of additional weapons deliveries. The rhetoric marks an escalation in Moscow\'s diplomatic positioning.',
    bsScore: 70,
    biasAnalysis: 'Al Jazeera presents Russian government statements with appropriate attribution and context.',
    credibilityTier: 3,
    isBreaking: false,
  },
  {
    id: 'ukr-005',
    title: 'Wagner Group Activities Reported in Belarus Near Polish Border',
    source: 'Deutsche Welle',
    sourceReliability: 4,
    sourceBias: -0.2,
    category: 'conflict',
    country: 'Belarus',
    countryCode: 'BY',
    lat: 53.9045,
    lng: 27.5615,
    publishedAt: '2026-03-17T09:00:00Z',
    url: 'https://example.com/article/ukr-005',
    summary: 'Satellite imagery and local reports indicate Wagner mercenary presence at a training facility in western Belarus, raising concerns in Poland and the Baltic states about potential destabilization operations along NATO\'s eastern flank.',
    bsScore: 78,
    biasAnalysis: 'DW provides factual reporting with emphasis on regional security concerns.',
    credibilityTier: 2,
    isBreaking: false,
  },
];

export default articles;
