import { Article } from './types';

// Seed data for SITREP - Part 2: China/Taiwan, Middle East (Articles 16-30)
export const articlesPart2: Article[] = [
  // CHINA/TAIWAN
  {
    id: 'chn-001',
    title: 'Taiwan Reports Largest Chinese Military Exercise Near Strait This Year',
    source: 'Bloomberg',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'conflict',
    country: 'Taiwan',
    countryCode: 'TW',
    lat: 25.033,
    lng: 121.5654,
    publishedAt: '2026-03-20T04:00:00Z',
    url: 'https://example.com/article/chn-001',
    summary: 'Taiwan\'s defense ministry detected 45 Chinese military aircraft and 8 naval vessels operating near the median line, the largest such deployment since October. The exercises coincide with a high-level US delegation visit to Taipei.',
    bsScore: 88,
    biasAnalysis: 'Bloomberg provides factual reporting focused on market and geopolitical implications.',
    credibilityTier: 1,
    isBreaking: true,
  },
  {
    id: 'chn-002',
    title: 'China Imposes New Trade Restrictions on Critical Mineral Exports',
    source: 'Reuters',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'economy',
    country: 'China',
    countryCode: 'CN',
    lat: 39.9042,
    lng: 116.4074,
    publishedAt: '2026-03-19T08:00:00Z',
    url: 'https://example.com/article/chn-002',
    summary: 'Beijing announced export licensing requirements for rare earth minerals essential for semiconductor and electric vehicle manufacturing. The move is seen as retaliation for US technology restrictions and could disrupt global supply chains.',
    bsScore: 91,
    biasAnalysis: 'Reuters provides balanced coverage of trade policy with industry impact analysis.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'chn-003',
    title: 'TSMC Confirms Second Arizona Fab Construction Ahead of Schedule',
    source: 'Wall Street Journal',
    sourceReliability: 4,
    sourceBias: 0.2,
    category: 'tech',
    country: 'United States',
    countryCode: 'US',
    lat: 33.3062,
    lng: -111.8413,
    publishedAt: '2026-03-18T15:00:00Z',
    url: 'https://example.com/article/chn-003',
    summary: 'Taiwan Semiconductor Manufacturing Co. announced its second Arizona fabrication facility will begin production in 2027, citing strong demand from US tech companies and CHIPS Act incentives. The facility represents $65 billion in total investment.',
    bsScore: 85,
    biasAnalysis: 'WSJ provides business-focused reporting with emphasis on economic implications.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'chn-004',
    title: 'Chinese AI Startup Claims Breakthrough in Quantum-Classical Hybrid Computing',
    source: 'South China Morning Post',
    sourceReliability: 3,
    sourceBias: -0.3,
    category: 'tech',
    country: 'China',
    countryCode: 'CN',
    lat: 31.2304,
    lng: 121.4737,
    publishedAt: '2026-03-17T10:30:00Z',
    url: 'https://example.com/article/chn-004',
    summary: 'A Shanghai-based research team announced a novel architecture combining quantum processors with classical systems, claiming significant speedups for specific optimization problems. Independent verification is pending.',
    bsScore: 65,
    biasAnalysis: 'SCMP presents Chinese technology developments with some promotional framing.',
    credibilityTier: 3,
    isBreaking: false,
  },
  {
    id: 'chn-005',
    title: 'US Navy Conducts Freedom of Navigation Operation in South China Sea',
    source: 'AP',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'conflict',
    country: 'Philippines',
    countryCode: 'PH',
    lat: 11.3333,
    lng: 115.8833,
    publishedAt: '2026-03-16T06:00:00Z',
    url: 'https://example.com/article/chn-005',
    summary: 'A US guided-missile destroyer sailed near disputed islands claimed by China, prompting condemnation from Beijing. The operation challenged what the US considers excessive maritime claims in international waters.',
    bsScore: 92,
    biasAnalysis: 'AP provides factual, neutral reporting on military operations with official statements from both sides.',
    credibilityTier: 1,
    isBreaking: false,
  },

  // MIDDLE EAST
  {
    id: 'me-001',
    title: 'Israeli Airstrikes Target Hezbollah Positions in Southern Lebanon',
    source: 'BBC',
    sourceReliability: 4,
    sourceBias: -0.1,
    category: 'conflict',
    country: 'Lebanon',
    countryCode: 'LB',
    lat: 33.2722,
    lng: 35.2033,
    publishedAt: '2026-03-20T14:00:00Z',
    url: 'https://example.com/article/me-001',
    summary: 'Israeli warplanes struck what the IDF described as Hezbollah weapons depots and command centers near the border. Lebanon reported civilian casualties, while Israel maintained the strikes were preemptive after rocket fire.',
    bsScore: 82,
    biasAnalysis: 'BBC provides balanced coverage with attribution of claims from both Israeli and Lebanese sources.',
    credibilityTier: 1,
    isBreaking: true,
  },
  {
    id: 'me-002',
    title: 'Houthi Attacks Disrupt Red Sea Shipping for Third Consecutive Week',
    source: 'Financial Times',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'conflict',
    country: 'Yemen',
    countryCode: 'YE',
    lat: 14.9086,
    lng: 42.7607,
    publishedAt: '2026-03-19T11:30:00Z',
    url: 'https://example.com/article/me-002',
    summary: 'Major shipping lines continue rerouting around the Cape of Good Hope as Houthi rebels target commercial vessels in the Red Sea. The disruption has increased shipping costs by 40% and threatens global supply chains.',
    bsScore: 89,
    biasAnalysis: 'FT provides factual reporting focused on economic and logistical impacts.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'me-003',
    title: 'Saudi Arabia and Iran Announce Joint Economic Cooperation Committee',
    source: 'Al Jazeera',
    sourceReliability: 3,
    sourceBias: -0.3,
    category: 'politics',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    lat: 24.7136,
    lng: 46.6753,
    publishedAt: '2026-03-18T09:00:00Z',
    url: 'https://example.com/article/me-003',
    summary: 'A year after restoring diplomatic relations, Saudi Arabia and Iran established a bilateral committee to explore trade and investment opportunities. The move represents a significant shift in regional dynamics brokered by China.',
    bsScore: 72,
    biasAnalysis: 'Al Jazeera presents the development positively with emphasis on regional diplomacy.',
    credibilityTier: 3,
    isBreaking: false,
  },
  {
    id: 'me-004',
    title: 'Gaza Humanitarian Crisis Deepens as Aid Deliveries Halted',
    source: 'The Guardian',
    sourceReliability: 4,
    sourceBias: -0.5,
    category: 'conflict',
    country: 'Palestine',
    countryCode: 'PS',
    lat: 31.5017,
    lng: 34.4668,
    publishedAt: '2026-03-21T08:00:00Z',
    url: 'https://example.com/article/me-004',
    summary: 'UN agencies report catastrophic conditions in Gaza as border crossings remain closed and humanitarian corridors are blocked. Aid organizations warn of imminent famine affecting over 2 million people.',
    bsScore: 70,
    biasAnalysis: 'The Guardian emphasizes humanitarian concerns with limited Israeli government perspective.',
    credibilityTier: 2,
    isBreaking: true,
  },
  {
    id: 'me-005',
    title: 'UAE Announces Major AI Investment Partnership with US Tech Firms',
    source: 'Bloomberg',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'tech',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    lat: 24.4539,
    lng: 54.3773,
    publishedAt: '2026-03-17T12:00:00Z',
    url: 'https://example.com/article/me-005',
    summary: 'Abu Dhabi\'s sovereign wealth fund pledged $25 billion toward AI infrastructure projects in partnership with OpenAI, Microsoft, and NVIDIA. The deal includes data center construction and AI research facilities.',
    bsScore: 88,
    biasAnalysis: 'Bloomberg provides factual business reporting on investment deals.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'me-006',
    title: 'Turkish Central Bank Raises Rates to Combat Persistent Inflation',
    source: 'Reuters',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'economy',
    country: 'Turkey',
    countryCode: 'TR',
    lat: 39.9334,
    lng: 32.8597,
    publishedAt: '2026-03-16T11:00:00Z',
    url: 'https://example.com/article/me-006',
    summary: 'Turkey\'s central bank increased its key interest rate by 500 basis points to 55%, continuing a dramatic policy reversal under the new economic team. Inflation remains above 60% despite aggressive tightening.',
    bsScore: 91,
    biasAnalysis: 'Reuters provides factual reporting on monetary policy with economic context.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'me-007',
    title: 'Iran Nuclear Facility Inspections Resume After Six-Month Gap',
    source: 'BBC',
    sourceReliability: 4,
    sourceBias: -0.1,
    category: 'politics',
    country: 'Iran',
    countryCode: 'IR',
    lat: 35.6892,
    lng: 51.389,
    publishedAt: '2026-03-15T13:00:00Z',
    url: 'https://example.com/article/me-007',
    summary: 'IAEA inspectors gained access to Iranian nuclear facilities after months of negotiations, though full monitoring capabilities have not been restored. The development comes amid stalled talks on reviving the nuclear agreement.',
    bsScore: 85,
    biasAnalysis: 'BBC provides measured reporting on diplomatic developments with international context.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'me-008',
    title: 'Syrian Refugee Crisis Strains Jordanian Resources',
    source: 'NPR',
    sourceReliability: 4,
    sourceBias: -0.3,
    category: 'politics',
    country: 'Jordan',
    countryCode: 'JO',
    lat: 31.9454,
    lng: 35.9284,
    publishedAt: '2026-03-14T10:00:00Z',
    url: 'https://example.com/article/me-008',
    summary: 'Jordan\'s government appealed for increased international support as it hosts over 1.3 million Syrian refugees, representing roughly 10% of the country\'s population. Water and electricity shortages are acute in border camps.',
    bsScore: 78,
    biasAnalysis: 'NPR provides empathetic coverage of humanitarian issues with policy context.',
    credibilityTier: 1,
    isBreaking: false,
  },
  {
    id: 'me-009',
    title: 'OPEC+ Extends Production Cuts Through Q3 2026',
    source: 'Wall Street Journal',
    sourceReliability: 4,
    sourceBias: 0.2,
    category: 'economy',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    lat: 24.7136,
    lng: 46.6753,
    publishedAt: '2026-03-13T14:00:00Z',
    url: 'https://example.com/article/me-009',
    summary: 'OPEC and allied producers agreed to maintain voluntary production cuts of 2.2 million barrels per day through September, citing market uncertainty and rising non-OPEC supply. Oil prices rose 3% on the announcement.',
    bsScore: 87,
    biasAnalysis: 'WSJ provides business-focused reporting on energy markets.',
    credibilityTier: 2,
    isBreaking: false,
  },
  {
    id: 'me-010',
    title: 'Egypt Discovers Major Natural Gas Field in Mediterranean',
    source: 'Reuters',
    sourceReliability: 5,
    sourceBias: 0,
    category: 'economy',
    country: 'Egypt',
    countryCode: 'EG',
    lat: 30.0444,
    lng: 31.2357,
    publishedAt: '2026-03-12T09:00:00Z',
    url: 'https://example.com/article/me-010',
    summary: 'Egyptian authorities announced discovery of a natural gas field estimated to contain 3.5 trillion cubic feet of reserves. The find could boost Egypt\'s position as a regional energy hub and reduce dependence on imports.',
    bsScore: 86,
    biasAnalysis: 'Reuters provides factual reporting on energy discoveries with economic implications.',
    credibilityTier: 1,
    isBreaking: false,
  },
];

export default articlesPart2;
